"""
Komal Mart (कोमल मार्ट) — Master Database Seed Data
Authentic Indian Kirana & General Store inventory for Wadala, Mumbai.
Contains 13 categories, 110+ staple products with realistic retail prices, MRPs,
30kg bori options for loose grains, ₹10/₹20/₹50 pouches for spices, 1L & 5L dibba oils,
dry fruit wholesale 5kg+ tiers, biscuits (no chips, no chocolates), and verified local images.
"""

CATEGORIES_DATA = [
    {
        "name": "Dals & Pulses",
        "name_hi": "डाळी व कडधान्ये",
        "slug": "dals-pulses",
        "icon": "beans",
        "display_order": 1
    },
    {
        "name": "Atta, Flours & Whole Grains",
        "name_hi": "पीठ, मैदा व अखंड धान्य",
        "slug": "atta-flours",
        "icon": "wheat",
        "display_order": 2
    },
    {
        "name": "Rice & Mandi Staples",
        "name_hi": "तांदूळ, पोहे व साबुदाणा",
        "slug": "rice-grains",
        "icon": "grain",
        "display_order": 3
    },
    {
        "name": "Beans & Legumes",
        "name_hi": "कडधान्ये व राजमा / छोले",
        "slug": "beans-legumes",
        "icon": "shapes",
        "display_order": 4
    },
    {
        "name": "Dry Fruits & Nuts",
        "name_hi": "सुका मेवा (किरकोळ व घाऊक ५ किलो+)",
        "slug": "dry-fruits-nuts",
        "icon": "sparkles",
        "display_order": 5
    },
    {
        "name": "Edible Oils & Desi Ghee",
        "name_hi": "खाद्यतेल व शुद्ध तूप",
        "slug": "oils-ghee",
        "icon": "droplet",
        "display_order": 6
    },
    {
        "name": "Spices & Salt (Masale)",
        "name_hi": "मसाले व मीठ",
        "slug": "spices-masalas",
        "icon": "flame",
        "display_order": 7
    },
    {
        "name": "Sugar, Jaggery & Sweeteners",
        "name_hi": "साखर व गूळ",
        "slug": "sugar-jaggery",
        "icon": "sparkles",
        "display_order": 8
    },
    {
        "name": "Tea, Coffee & Beverages",
        "name_hi": "चहा, कॉफी व पेये",
        "slug": "tea-beverages",
        "icon": "coffee",
        "display_order": 9
    },
    {
        "name": "Biscuits & Bakery",
        "name_hi": "बिस्किटे व टोस्ट",
        "slug": "biscuits-bakery",
        "icon": "shopping-bag",
        "display_order": 10
    },
    {
        "name": "Cold Drinks & Bottled Water",
        "name_hi": "शीतपेये व मिनरल वॉटर",
        "slug": "cold-drinks",
        "icon": "droplet",
        "display_order": 11
    },
    {
        "name": "Cleaning & Detergents",
        "name_hi": "स्वच्छता व डिटर्जंट",
        "slug": "household-cleaning",
        "icon": "trash",
        "display_order": 12
    },
    {
        "name": "Personal Care & Pooja",
        "name_hi": "पर्सनल केअर व पूजा साहित्य",
        "slug": "pooja-samagri",
        "icon": "sparkles",
        "display_order": 13
    }
]

PRODUCTS_DATA = [   {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'अस्सल गावरान अनपॉलिश्ड तूर डाळ. चवदार, लवकर शिजणारी आणि पचनास हलकी.',
        'image_url': '/products/toor-daal-gavran.jpg',
        'is_loose': True,
        'name': 'Toor Dal / Arhar Dal (Gavran Unpolished Loose)',
        'name_hi': 'तूर डाळ (गावरान मोकळी)',
        'variants': [   {'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 100, 'unit_size': '500g'},
                        {'mrp': 190.0, 'selling_price': 190.0, 'stock_quantity': 150, 'unit_size': '1kg'},
                        {'mrp': 380.0, 'selling_price': 380.0, 'stock_quantity': 50, 'unit_size': '2kg'},
                        {'mrp': 950.0, 'selling_price': 930.0, 'stock_quantity': 25, 'unit_size': '5kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'स्वच्छ आणि निवडलेली चना डाळ. पुरणपोळी आणि बेसनासाठी उत्तम दर्जा.',
        'image_url': '/products/chana-daal-loose.jpg',
        'is_loose': True,
        'name': 'Chana Dal (Bengal Gram Split Loose)',
        'name_hi': 'चना डाळ (हरभरा डाळ मोकळी)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 100, 'unit_size': '500g'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 150, 'unit_size': '1kg'},
                        {'mrp': 180.0, 'selling_price': 180.0, 'stock_quantity': 50, 'unit_size': '2kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'पिवळी मूंग डाळ. हलकी, पचायला सोपी, आजारी व्यक्ती व मुलांसाठी खिचडी स्पेशल.',
        'image_url': '/products/moong-daal-yellow.jpg',
        'is_loose': True,
        'name': 'Moong Dal Dhuli (Yellow Split Loose)',
        'name_hi': 'धुली मूंग डाळ (पिवळी मोकळी)',
        'variants': [   {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 120.0, 'selling_price': 120.0, 'stock_quantity': 100, 'unit_size': '1kg'},
                        {'mrp': 240.0, 'selling_price': 240.0, 'stock_quantity': 40, 'unit_size': '2kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'हिरवी सालीची मूंग डाळ. फायबरयुक्त, पौष्टिक आणि खिचडी स्पेशल.',
        'image_url': '/products/moong-daal-chilka.jpg',
        'is_loose': True,
        'name': 'Moong Dal Chilka (Green Split Loose)',
        'name_hi': 'मूंग डाळ छिलका (हिरवी टूक मोकळी)',
        'variants': [   {'mrp': 58.0, 'selling_price': 58.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 115.0, 'selling_price': 115.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'मोड आणण्यासाठी आणि उसळीसाठी अस्सल गावरान हिरवे मूग.',
        'image_url': '/products/moong-sabut.jpg',
        'is_loose': True,
        'name': 'Moong Sabut (Whole Green Moong Loose)',
        'name_hi': 'अखंड हिरवे मूग (गावरान मोकळे)',
        'variants': [   {'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 110.0, 'selling_price': 110.0, 'stock_quantity': 80, 'unit_size': '1kg'},
                        {'mrp': 220.0, 'selling_price': 220.0, 'stock_quantity': 30, 'unit_size': '2kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'इडली, डोसा आणि मेदू वड्यासाठी पांढरी शुभ्र उडीद डाळ. उत्तम आंबवणे (fermentation).',
        'image_url': '/products/urad-daal-dhuli.jpg',
        'is_loose': True,
        'name': 'Urad Dal Dhuli (White Split Idli Dal Loose)',
        'name_hi': 'धुली उडीद डाळ (सफेद - इडली/डोसा मोकळी)',
        'variants': [   {'mrp': 65.0, 'selling_price': 65.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 130.0, 'selling_price': 130.0, 'stock_quantity': 100, 'unit_size': '1kg'},
                        {'mrp': 260.0, 'selling_price': 260.0, 'stock_quantity': 40, 'unit_size': '2kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'काळी सालीची उडीद डाळ. दाल मखनी आणि पौष्टिक डाळीसाठी उत्तम.',
        'image_url': '/products/urad-daal-black.jpg',
        'is_loose': True,
        'name': 'Kali Urad Dal (Split Black Gram Loose)',
        'name_hi': 'काळी उडीद डाळ (छिलका मोकळी)',
        'variants': [   {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 50, 'unit_size': '500g'},
                        {'mrp': 120.0, 'selling_price': 120.0, 'stock_quantity': 70, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'लाल मसूर डाळ. झटपट शिजणारी आणि दैनंदिन जेवणासाठी चवदार.',
        'image_url': '/products/masoor-daal-red.jpg',
        'is_loose': True,
        'name': 'Masoor Dal Lal (Split Red Lentils Loose)',
        'name_hi': 'लाल मसूर डाळ (मोकळी)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dals-pulses',
        'description': 'अख्खा तपकिरी मसूर. अस्सल कोल्हापुरी व मालवणी उसळीसाठी अप्रतिम.',
        'image_url': '/products/akha-masoor.jpg',
        'is_loose': True,
        'name': 'Akha Masoor (Whole Brown Lentils Loose)',
        'name_hi': 'अख्खा मसूर (मोकळा उसळ स्पेशल)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': '१००% शुद्ध गव्हाचे ताजे दळलेले चक्की पीठ. मऊ लुसलुशीत पोळ्या होतात.',
        'image_url': '/products/chakki-atta-loose.jpg',
        'is_loose': True,
        'name': 'Chakki Fresh Whole Wheat Atta (Fresh Ground Loose)',
        'name_hi': 'चक्की फ्रेश गव्हाचे पीठ (ताज्या चक्कीचे मोकळे)',
        'variants': [   {'mrp': 38.0, 'selling_price': 38.0, 'stock_quantity': 100, 'unit_size': '1kg'},
                        {'mrp': 76.0, 'selling_price': 76.0, 'stock_quantity': 80, 'unit_size': '2kg'},
                        {'mrp': 190.0, 'selling_price': 190.0, 'stock_quantity': 60, 'unit_size': '5kg'},
                        {'mrp': 380.0, 'selling_price': 375.0, 'stock_quantity': 30, 'unit_size': '10kg'}]},
    {   'brand': 'Aashirvaad',
        'category_slug': 'atta-flours',
        'description': 'आशीर्वाद १००% संपूर्ण गव्हाचे चक्की पीठ. नैसर्गिक फायबरयुक्त.',
        'image_url': '/products/aashirvaad-atta.jpg',
        'is_loose': False,
        'name': 'Aashirvaad Shudh Chakki Atta (5kg / 10kg)',
        'name_hi': 'आशीर्वाद शुद्ध चक्की आटा (५ किलो / १० किलो)',
        'variants': [   {'mrp': 245.0, 'selling_price': 245.0, 'stock_quantity': 30, 'unit_size': '5kg Bag'},
                        {'mrp': 480.0, 'selling_price': 480.0, 'stock_quantity': 20, 'unit_size': '10kg Bag'}]},
    {   'brand': 'Fortune',
        'category_slug': 'atta-flours',
        'description': 'फॉर्च्युन चक्की फ्रेश आटा. पारंपरिक चक्की पद्धतीने दळलेले मऊ पोळ्यांचे पीठ.',
        'image_url': '/products/fortune-atta.jpg',
        'is_loose': False,
        'name': 'Fortune Chakki Fresh Atta (5kg / 10kg)',
        'name_hi': 'फॉर्च्युन चक्की फ्रेश आटा (५ किलो / १० किलो)',
        'variants': [   {'mrp': 230.0, 'selling_price': 230.0, 'stock_quantity': 25, 'unit_size': '5kg Bag'},
                        {'mrp': 450.0, 'selling_price': 450.0, 'stock_quantity': 15, 'unit_size': '10kg Bag'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'मध्य प्रदेशचा अस्सल लोकवान गहू. मोठा टपोरा दाणा, गोडवा आणि चवदार पोळ्यांसाठी.',
        'image_url': '/products/mp-lokwan-wheat.jpg',
        'is_loose': True,
        'name': 'MP Lokwan Wheat Grain (Desi Gehu Loose)',
        'name_hi': 'मध्य प्रदेश लोकवान गहू (मोकळा व ३० किलो बोरी)',
        'variants': [   {'mrp': 42.0, 'selling_price': 42.0, 'stock_quantity': 100, 'unit_size': '1kg'},
                        {'mrp': 210.0, 'selling_price': 210.0, 'stock_quantity': 80, 'unit_size': '5kg'},
                        {'mrp': 420.0, 'selling_price': 420.0, 'stock_quantity': 50, 'unit_size': '10kg'},
                        {'mrp': 1260.0, 'selling_price': 1230.0, 'stock_quantity': 20, 'unit_size': '30kg Bori'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'प्रीमियम सीहोर शरबती गहू. सोनेरी चकचकीत दाणा, सर्वाधिक मऊ पोळ्या आणि अप्रतिम चव.',
        'image_url': '/products/mp-sharbati-wheat.jpg',
        'is_loose': True,
        'name': 'MP Sharbati Premium Wheat Grain (Loose)',
        'name_hi': 'मध्य प्रदेश शरबती प्रीमियम गहू (मोकळा व ३० किलो बोरी)',
        'variants': [   {'mrp': 48.0, 'selling_price': 48.0, 'stock_quantity': 80, 'unit_size': '1kg'},
                        {'mrp': 240.0, 'selling_price': 240.0, 'stock_quantity': 60, 'unit_size': '5kg'},
                        {'mrp': 480.0, 'selling_price': 480.0, 'stock_quantity': 40, 'unit_size': '10kg'},
                        {'mrp': 1440.0, 'selling_price': 1410.0, 'stock_quantity': 15, 'unit_size': '30kg Bori'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'अस्सल देशी गावरान गहू. नैसर्गिक, पौष्टिक आणि दैनंदिन दळणासाठी उत्कृष्ट निवड.',
        'image_url': '/products/desi-gavran-wheat.jpg',
        'is_loose': True,
        'name': 'Desi Gavran Whole Wheat Grain (Loose)',
        'name_hi': 'देशी गावरान गहू (मोकळा व ३० किलो बोरी)',
        'variants': [   {'mrp': 40.0, 'selling_price': 40.0, 'stock_quantity': 100, 'unit_size': '1kg'},
                        {'mrp': 200.0, 'selling_price': 200.0, 'stock_quantity': 80, 'unit_size': '5kg'},
                        {'mrp': 400.0, 'selling_price': 400.0, 'stock_quantity': 50, 'unit_size': '10kg'},
                        {'mrp': 1200.0, 'selling_price': 1170.0, 'stock_quantity': 25, 'unit_size': '30kg Bori'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'बारीक पांढरा शुभ्र मैदा. समोसा, भटुरे, केक व खारी-बिस्किटांसाठी उत्तम.',
        'image_url': '/products/maida-loose.jpg',
        'is_loose': True,
        'name': 'Premium Maida (Refined All-Purpose Flour Loose)',
        'name_hi': 'प्रीमियम मैदा (मोकळा)',
        'variants': [   {'mrp': 22.0, 'selling_price': 22.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 44.0, 'selling_price': 44.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': '१००% शुद्ध हरभरा डाळीचे बारीक दळलेले ताजे बेसन. भजी, लाडू व पिठल्यासाठी.',
        'image_url': '/products/besan-loose.jpg',
        'is_loose': True,
        'name': 'Pure Chana Dal Besan (Gram Flour Loose)',
        'name_hi': 'शुद्ध हरभरा डाळीचे बेसन (मोकळे)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 100, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'चक्कीवर खास दळलेले दाणेदार बेसन. बेसन लाडू, ढोकळा व चकलीसाठी दाणेदार चव.',
        'image_url': '/products/fresh-chakki-besan.jpg',
        'is_loose': True,
        'name': 'Fresh Chakki Besan (Coarse Motu Besan Loose)',
        'name_hi': 'ताज्या चक्कीचे जाडे बेसन (लाडू स्पेशल)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Nimraj',
        'category_slug': 'atta-flours',
        'description': 'निमराज ब्रँडेड सीलबंद चक्की फ्रेश चणा बेसन. हमखास स्वच्छता आणि गुणवत्ता.',
        'image_url': '/products/nimraj-besan-500g.jpg',
        'is_loose': False,
        'name': 'Nimraj Pure Chana Besan (500g Pack)',
        'name_hi': 'निमराज शुद्ध चक्की बेसन (५०० ग्रॅम पॅक)',
        'variants': [{'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 40, 'unit_size': '500g Pack'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'बारीक स्वच्छ रवा. शिरा, उपमा आणि रव्याचा डोसा बनवण्यासाठी ताजा.',
        'image_url': '/products/sooji-rawa-loose.jpg',
        'is_loose': True,
        'name': 'Sooji / Rawa (Semolina Loose)',
        'name_hi': 'सुजी / रवा (मोकळा)',
        'variants': [   {'mrp': 22.0, 'selling_price': 22.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 44.0, 'selling_price': 44.0, 'stock_quantity': 100, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'बारीक पांढरे तांदळाचे पीठ. मऊ तांदळाची भाकरी, घावणे व मोदकाची उकड यासाठी.',
        'image_url': '/products/rice-flour-loose.jpg',
        'is_loose': True,
        'name': 'Fresh Rice Flour / Chawal Ka Atta (Loose)',
        'name_hi': 'तांदळाचे पीठ (मोकळे घावणे/भाकरी स्पेशल)',
        'variants': [   {'mrp': 25.0, 'selling_price': 25.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'पांढरी शुभ्र शाळू ज्वारी. उत्तम पौष्टिक भाकरीसाठी चवदार दाणा.',
        'image_url': '/products/jowar-grain-loose.jpg',
        'is_loose': True,
        'name': 'Jowar Grain (White Sorghum Loose)',
        'name_hi': 'शाळू ज्वारी अखंड (मोकळी व ३० किलो बोरी)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 80, 'unit_size': '1kg'},
                        {'mrp': 225.0, 'selling_price': 225.0, 'stock_quantity': 50, 'unit_size': '5kg'},
                        {'mrp': 1350.0, 'selling_price': 1320.0, 'stock_quantity': 15, 'unit_size': '30kg Bori'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'गावरान बाजरी. हिवाळा आणि वर्षभर उष्ण व पौष्टिक बाजरीच्या भाकरीसाठी.',
        'image_url': '/products/bajra-grain-loose.jpg',
        'is_loose': True,
        'name': 'Bajra Grain (Pearl Millet Loose)',
        'name_hi': 'बाजरी अखंड (मोकळी व ३० किलो बोरी)',
        'variants': [   {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 80, 'unit_size': '1kg'},
                        {'mrp': 175.0, 'selling_price': 175.0, 'stock_quantity': 50, 'unit_size': '5kg'},
                        {'mrp': 1050.0, 'selling_price': 1020.0, 'stock_quantity': 15, 'unit_size': '30kg Bori'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'atta-flours',
        'description': 'कॅल्शियम आणि आयर्नयुक्त लाल नाचणी. सत्त्व, भाकरी व लहान मुलांच्या पेजसाठी उत्तम.',
        'image_url': '/products/nachni-ragi-loose.jpg',
        'is_loose': True,
        'name': 'Nachni Grain (Ragi / Finger Millet Loose)',
        'name_hi': 'नाचणी अखंड (मोकळी पौष्टिक)',
        'variants': [   {'mrp': 25.0, 'selling_price': 25.0, 'stock_quantity': 50, 'unit_size': '500g'},
                        {'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 60, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'rice-grains',
        'description': 'मुंबईकरांचा आवडता वाडा कोलम तांदूळ. मऊ, सुटसुटीत आणि रोजच्या जेवणासाठी चवदार.',
        'image_url': '/products/wada-kolam-rice.jpg',
        'is_loose': True,
        'name': 'Wada Kolam Rice (Daily Mandi Loose Rice)',
        'name_hi': 'वाडा कोलम तांदूळ (मोकळा व ३० किलो बोरी)',
        'variants': [   {'mrp': 62.0, 'selling_price': 62.0, 'stock_quantity': 150, 'unit_size': '1kg'},
                        {'mrp': 310.0, 'selling_price': 310.0, 'stock_quantity': 100, 'unit_size': '5kg'},
                        {'mrp': 620.0, 'selling_price': 620.0, 'stock_quantity': 60, 'unit_size': '10kg'},
                        {'mrp': 1860.0, 'selling_price': 1800.0, 'stock_quantity': 25, 'unit_size': '30kg Bori'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'rice-grains',
        'description': 'सुवासिक लांब दाण्याचा अस्सल बासमती तांदूळ. पुलाव, बिर्याणी व सणासुदीच्या जेवणासाठी.',
        'image_url': '/products/basmati-rice-long.jpg',
        'is_loose': True,
        'name': 'Premium Long Grain Basmati Rice (Loose)',
        'name_hi': 'प्रीमियम बासमती तांदूळ (अखंड लांब दाणा मोकळा)',
        'variants': [   {'mrp': 120.0, 'selling_price': 120.0, 'stock_quantity': 80, 'unit_size': '1kg'},
                        {'mrp': 600.0, 'selling_price': 600.0, 'stock_quantity': 40, 'unit_size': '5kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'rice-grains',
        'description': 'किफायतशीर बासमती तुकडा. अप्रतिम सुगंध आणि रोजच्या स्वादिष्ट भातासाठी उत्तम.',
        'image_url': '/products/basmati-tukda-rice.jpg',
        'is_loose': True,
        'name': 'Basmati Rice Tukda / Tibar (Mandi Loose)',
        'name_hi': 'बासमती तुकडा तांदूळ (मोकळा सुगंधित)',
        'variants': [   {'mrp': 65.0, 'selling_price': 65.0, 'stock_quantity': 100, 'unit_size': '1kg'},
                        {'mrp': 325.0, 'selling_price': 325.0, 'stock_quantity': 60, 'unit_size': '5kg'},
                        {'mrp': 650.0, 'selling_price': 650.0, 'stock_quantity': 30, 'unit_size': '10kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'rice-grains',
        'description': 'मध्य प्रदेश स्पेशल जाडा पोहा. सकाळी गरमागरम आणि मऊ कांदा पोहे बनवण्यासाठी उत्तम.',
        'image_url': '/products/thick-jada-poha.jpg',
        'is_loose': True,
        'name': 'Thick Poha / Jada Poha for Kanda Poha (Loose)',
        'name_hi': 'जाडा पोहा (कांदा पोहा स्पेशल मोकळा)',
        'variants': [   {'mrp': 25.0, 'selling_price': 25.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 100, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'rice-grains',
        'description': 'बारीक कागदी पातळ पोहा. दिवाळी व घरगुती कुरकुरीत भाजका चिवडा बनवण्यासाठी.',
        'image_url': '/products/thin-patla-poha.jpg',
        'is_loose': True,
        'name': 'Thin Poha / Patla Poha for Chivda (Loose)',
        'name_hi': 'पातळ पोहा (कुरकुरीत चिवडा स्पेशल मोकळा)',
        'variants': [   {'mrp': 28.0, 'selling_price': 28.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'rice-grains',
        'description': 'मोतीसारखा चकचकीत साबुदाणा. उपवासाची मोकळी खिचडी आणि कुरकुरीत वड्यासाठी.',
        'image_url': '/products/sabudana-sago.jpg',
        'is_loose': True,
        'name': 'Nylon Sabudana / Sago Pearls (Loose)',
        'name_hi': 'नायलॉन साबुदाणा (उपवास स्पेशल मोकळा)',
        'variants': [   {'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 80, 'unit_size': '250g'},
                        {'mrp': 38.0, 'selling_price': 38.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 100, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'देशी काळा चणा. मोड आणून उसळ व काळा मसाला भाजीसाठी प्रथिनयुक्त.',
        'image_url': '/products/desi-kala-chana.jpg',
        'is_loose': True,
        'name': 'Desi Kala Chana (Brown Chickpeas Loose)',
        'name_hi': 'देशी काळा चणा (उसळ स्पेशल मोकळा)',
        'variants': [   {'mrp': 42.0, 'selling_price': 42.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 84.0, 'selling_price': 84.0, 'stock_quantity': 100, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'मोठ्या आकाराचे पांढरे काबुली चणे. अमृतसर छोले-भटुरे व चाटसाठी उत्कृष्ट.',
        'image_url': '/products/kabuli-chana-chhole.jpg',
        'is_loose': True,
        'name': 'Kabuli Chana / White Chickpeas (Loose Mandi)',
        'name_hi': 'काबुली चणा / छोले (मोठे पांढरे मोकळे)',
        'variants': [   {'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 150.0, 'selling_price': 150.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'अस्सल लहान काश्मिरी लाल राजमा. चवदार रस्सा आणि राजमा-चावल स्पेशल.',
        'image_url': '/products/kashmiri-red-rajma.jpg',
        'is_loose': True,
        'name': 'Kashmiri Red Rajma (Kidney Beans Loose)',
        'name_hi': 'काश्मिरी लाल राजमा (मोकळा)',
        'variants': [   {'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 150.0, 'selling_price': 150.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'निवडलेला पांढरा वाटाणा. मुंबईचा रगडा-पॅटिस आणि पाणीपुरीचा रगडा बनवण्यासाठी.',
        'image_url': '/products/safed-vatana.jpg',
        'is_loose': True,
        'name': 'Safed Vatana / White Dried Peas (Ragda Special)',
        'name_hi': 'सफेद वाटाणा (रगडा पॅटिस स्पेशल मोकळा)',
        'variants': [   {'mrp': 40.0, 'selling_price': 40.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 80.0, 'selling_price': 80.0, 'stock_quantity': 100, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'गोडसर हिरवा वाटाणा. मिसळ, उसळ आणि भाजीसाठी चवदार.',
        'image_url': '/products/green-vatana.jpg',
        'is_loose': True,
        'name': 'Green Vatana / Dried Green Peas (Loose Mandi)',
        'name_hi': 'हिरवा सुका वाटाणा (मोकळा उसळ स्पेशल)',
        'variants': [   {'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 110.0, 'selling_price': 110.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'कोकण स्पेशल काळा वाटाणा. अस्सल मालवणी काळ्या वाटाण्याची उसळ व सांबारासाठी.',
        'image_url': '/products/black-vatana.jpg',
        'is_loose': True,
        'name': 'Kala Vatana / Black Dried Peas (Mandi Loose)',
        'name_hi': 'काळा वाटाणा (मालवणी उसळ व सांबार स्पेशल)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 50, 'unit_size': '500g'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 70, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'पांढरी चवळी. मऊ शिजणारी आणि रसरशीत भाजीसाठी पौष्टिक कडधान्य.',
        'image_url': '/products/chavli-lobia.jpg',
        'is_loose': True,
        'name': 'Chavli / Black-Eyed Peas (Lobia Loose)',
        'name_hi': 'चवळी (मोकळी उसळ स्पेशल)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'beans-legumes',
        'description': 'अस्सल गावरान मटकी. झणझणीत मिसळ आणि मोड आलेल्या पौष्टिक उसळीसाठी.',
        'image_url': '/products/matki-beans.jpg',
        'is_loose': True,
        'name': 'Matki / Moth Beans Whole (Sprouting Lentils)',
        'name_hi': 'मटकी अखंड (मोड स्पेशल मोकळी)',
        'variants': [   {'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 110.0, 'selling_price': 110.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Dryfruits',
        'category_slug': 'dry-fruits-nuts',
        'description': '१००% गोड कॅलिफोर्निया बदाम गिरी. कुरकुरीत, तेलाने समृद्ध आणि बुद्धिवर्धक.',
        'image_url': '/products/california-almonds.jpg',
        'is_loose': True,
        'name': 'Premium California Almonds (Badam Giri Loose)',
        'name_hi': 'कॅलिफोर्निया बदाम (मोकळे व ५ किलो घाऊक)',
        'variants': [   {'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 100, 'unit_size': '50g Pouch'},
                        {'mrp': 225.0, 'selling_price': 225.0, 'stock_quantity': 80, 'unit_size': '250g'},
                        {'mrp': 440.0, 'selling_price': 440.0, 'stock_quantity': 50, 'unit_size': '500g'},
                        {'mrp': 860.0, 'selling_price': 860.0, 'stock_quantity': 40, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Dryfruits',
        'category_slug': 'dry-fruits-nuts',
        'description': 'प्रीमियम संपूर्ण काजू गर (W320). गोडसर, बिनकिडीचा आणि मिठायांसाठी उत्कृष्ट.',
        'image_url': '/products/cashew-kaju-w320.jpg',
        'is_loose': True,
        'name': 'Premium Whole Cashews (Kaju W320 Loose)',
        'name_hi': 'प्रीमियम काजू डब्ल्यू ३२० (मोकळा व ५ किलो घाऊक)',
        'variants': [   {'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 100, 'unit_size': '50g Pouch'},
                        {'mrp': 240.0, 'selling_price': 240.0, 'stock_quantity': 80, 'unit_size': '250g'},
                        {'mrp': 470.0, 'selling_price': 470.0, 'stock_quantity': 50, 'unit_size': '500g'},
                        {'mrp': 920.0, 'selling_price': 920.0, 'stock_quantity': 40, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Dryfruits',
        'category_slug': 'dry-fruits-nuts',
        'description': 'सांगली-तासगावचे अस्सल पिवळेधमक गोड बेदाणे. खीर, शिरा व आरोग्यासाठी उत्तम.',
        'image_url': '/products/golden-kishmish.jpg',
        'is_loose': True,
        'name': 'Indian Golden Raisins / Kishmish (Loose)',
        'name_hi': 'गोल्डन बेदाणे / मनुका (मोकळे व ५ किलो घाऊक)',
        'variants': [   {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 160.0, 'selling_price': 160.0, 'stock_quantity': 40, 'unit_size': '500g'},
                        {'mrp': 310.0, 'selling_price': 310.0, 'stock_quantity': 30, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Dryfruits',
        'category_slug': 'dry-fruits-nuts',
        'description': 'बिहारचे पांढरे स्वच्छ फुल मखाना. तुपात भाजून खाण्यासाठी कॅल्शियमयुक्त हलका स्नॅक.',
        'image_url': '/products/phool-makhana.jpg',
        'is_loose': True,
        'name': 'Phool Makhana / Lotus Seeds (Fox Nuts Loose)',
        'name_hi': 'फुल मखाना / कमळ गट्टा (मोकळा)',
        'variants': [   {'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 60, 'unit_size': '100g'},
                        {'mrp': 235.0, 'selling_price': 235.0, 'stock_quantity': 40, 'unit_size': '250g'},
                        {'mrp': 460.0, 'selling_price': 460.0, 'stock_quantity': 25, 'unit_size': '500g'},
                        {'mrp': 900.0, 'selling_price': 900.0, 'stock_quantity': 20, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'dry-fruits-nuts',
        'description': 'गोडसर तेलाने भरलेली सुक्या खोबऱ्याची वाटी. मसाला वाटण व मोदकाच्या सारणासाठी.',
        'image_url': '/products/sukha-khobra-copra.jpg',
        'is_loose': True,
        'name': 'Sukha Khobra / Dry Coconut Copra (Whole Loose)',
        'name_hi': 'सुके खोबरे / वाटी (मोकळे व १ किलो)',
        'variants': [   {'mrp': 65.0, 'selling_price': 65.0, 'stock_quantity': 80, 'unit_size': '250g'},
                        {'mrp': 130.0, 'selling_price': 130.0, 'stock_quantity': 60, 'unit_size': '500g'},
                        {'mrp': 250.0, 'selling_price': 250.0, 'stock_quantity': 40, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Dryfruits',
        'category_slug': 'dry-fruits-nuts',
        'description': 'गोड निवडलेली पिवळी खारीक. डिंकाचे लाडू, खारीक पावडर व आरोग्यासाठी पौष्टिक.',
        'image_url': '/products/kharik-dry-dates.jpg',
        'is_loose': True,
        'name': 'Kharik / Dry Dates (Loose Yellow/Black)',
        'name_hi': 'सुकी खारीक (पिवळी मोकळी)',
        'variants': [   {'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 150.0, 'selling_price': 150.0, 'stock_quantity': 40, 'unit_size': '500g'},
                        {'mrp': 290.0, 'selling_price': 290.0, 'stock_quantity': 30, 'unit_size': '1kg'}]},
    {   'brand': 'Fortune',
        'category_slug': 'oils-ghee',
        'description': 'फॉर्च्युन सनलाईट रिफाइंड सूर्यफूल तेल. हलके, पचायला सोपे आणि व्हिटॅमिनयुक्त.',
        'image_url': '/products/fortune-sunflower-oil-1l.jpg',
        'is_loose': False,
        'name': 'Fortune Sunlite Refined Sunflower Oil (1L Pouch)',
        'name_hi': 'फॉर्च्युन सनलाईट सूर्यफूल तेल (१ लिटर पाउच)',
        'variants': [{'mrp': 145.0, 'selling_price': 145.0, 'stock_quantity': 50, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Fortune',
        'category_slug': 'oils-ghee',
        'description': 'फॉर्च्युन सनलाईट ५ लिटर जार/कॅन. कौटुंबिक वापरासाठी किफायतशीर आणि स्वच्छ.',
        'image_url': '/products/fortune-sunflower-oil-5l.jpg',
        'is_loose': False,
        'name': 'Fortune Sunlite Refined Sunflower Oil (5L Can / Dibba)',
        'name_hi': 'फॉर्च्युन सूर्यफूल तेल (५ लिटर कॅन / डब्बा)',
        'variants': [{'mrp': 710.0, 'selling_price': 710.0, 'stock_quantity': 25, 'unit_size': '5L Can'}]},
    {   'brand': 'Fortune',
        'category_slug': 'oils-ghee',
        'description': 'फॉर्च्युन अस्सल कच्ची घानी शुद्ध मोहरीचे तेल. तिखट झणझणीत स्वाद आणि शुद्धता.',
        'image_url': '/products/fortune-mustard-oil-1l.jpg',
        'is_loose': False,
        'name': 'Fortune Kachi Ghani Mustard Oil (1L Pouch)',
        'name_hi': 'फॉर्च्युन कच्ची घानी मोहरीचे तेल (१ लिटर पाउच)',
        'variants': [{'mrp': 155.0, 'selling_price': 155.0, 'stock_quantity': 40, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Gemini',
        'category_slug': 'oils-ghee',
        'description': 'महाराष्ट्राचा नंबर १ विश्वास - जेमिनी शुद्ध सूर्यफूल तेल.',
        'image_url': '/products/gemini-sunflower-oil-1l.jpg',
        'is_loose': False,
        'name': 'Gemini Pure Refined Sunflower Oil (1L Pouch)',
        'name_hi': 'जेमिनी शुद्ध सूर्यफूल तेल (१ लिटर पाउच)',
        'variants': [{'mrp': 145.0, 'selling_price': 145.0, 'stock_quantity': 50, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Gemini',
        'category_slug': 'oils-ghee',
        'description': 'जेमिनी शुद्ध सूर्यफूल तेल ५ लिटर फॅमिली पॅक कॅन.',
        'image_url': '/products/gemini-sunflower-oil-5l.jpg',
        'is_loose': False,
        'name': 'Gemini Pure Refined Sunflower Oil (5L Can / Dibba)',
        'name_hi': 'जेमिनी सूर्यफूल तेल (५ लिटर डब्बा / कॅन)',
        'variants': [{'mrp': 710.0, 'selling_price': 710.0, 'stock_quantity': 25, 'unit_size': '5L Dibba'}]},
    {   'brand': 'Sun White',
        'category_slug': 'oils-ghee',
        'description': 'सन व्हाईट रिफाइंड सूर्यफूल तेल. खिशाला परवडणारे आणि शुद्ध स्वयंपाकाचे तेल.',
        'image_url': '/products/sun-white-sunflower-oil-1l.jpg',
        'is_loose': False,
        'name': 'Sun White Refined Sunflower Oil (1L Pouch)',
        'name_hi': 'सन व्हाईट सूर्यफूल तेल (१ लिटर पाउच)',
        'variants': [{'mrp': 135.0, 'selling_price': 135.0, 'stock_quantity': 40, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Priya',
        'category_slug': 'oils-ghee',
        'description': 'प्रिया गोल्ड रिफाइंड सूर्यफूल तेल. दैनंदिन स्वयंपाक व तळणासाठी उत्तम.',
        'image_url': '/products/priya-sunflower-oil-1l.jpg',
        'is_loose': False,
        'name': 'Priya Gold Refined Sunflower Oil (1L Pouch)',
        'name_hi': 'प्रिया गोल्ड सूर्यफूल तेल (१ लिटर पाउच)',
        'variants': [{'mrp': 135.0, 'selling_price': 135.0, 'stock_quantity': 40, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Sunpure',
        'category_slug': 'oils-ghee',
        'description': 'सनप्युअर कच्ची घानी शुद्ध मोहरीचे तेल. पारंपरिक घाणी पद्धतीने काढलेले.',
        'image_url': '/products/sunpure-mustard-oil-1l.jpg',
        'is_loose': False,
        'name': 'Sunpure Kachi Ghani Mustard Oil (1L Pouch)',
        'name_hi': 'सनप्युअर कच्ची घानी मोहरीचे तेल (१ लिटर पाउच)',
        'variants': [{'mrp': 150.0, 'selling_price': 150.0, 'stock_quantity': 35, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Engine Brand',
        'category_slug': 'oils-ghee',
        'description': 'अस्सल आग्रा इंजिन ब्रँड मोहरीचे तेल. अतिशय तीव्र आणि पारंपरिक स्वाद.',
        'image_url': '/products/engine-mustard-oil-1l.jpg',
        'is_loose': False,
        'name': 'Engine Brand Kachi Ghani Mustard Oil (1L Bottle)',
        'name_hi': 'इंजिन ब्रँड कच्ची घानी मोहरीचे तेल (१ लिटर बाटली)',
        'variants': [{'mrp': 175.0, 'selling_price': 175.0, 'stock_quantity': 30, 'unit_size': '1L Bottle'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'oils-ghee',
        'description': 'घाणीवर काढलेले शुद्ध मोहरीचे तेल. लोणचे आणि स्वयंपाकासाठी मोकळे तेल.',
        'image_url': '/products/pure-mustard-oil-loose.jpg',
        'is_loose': True,
        'name': 'Pure Mustard Oil / Sarson Tel (Loose Mandi)',
        'name_hi': 'शुद्ध मोहरीचे तेल (मोकळे १ लिटर / ५ लिटर)',
        'variants': [   {'mrp': 140.0, 'selling_price': 140.0, 'stock_quantity': 40, 'unit_size': '1L Bottle'},
                        {'mrp': 680.0, 'selling_price': 680.0, 'stock_quantity': 15, 'unit_size': '5L Can'}]},
    {   'brand': 'Palmolein',
        'category_slug': 'oils-ghee',
        'description': 'रिफाइंड पामोलिन तेल. भजी, वडे व फरसाण तळण्यासाठी उत्तम आणि किफायतशीर.',
        'image_url': '/products/palmolein-oil-1l.jpg',
        'is_loose': False,
        'name': 'Refined Palmolein Cooking Oil (1L Pouch)',
        'name_hi': 'पामोलिन तेल (१ लिटर पाउच तळण स्पेशल)',
        'variants': [{'mrp': 110.0, 'selling_price': 110.0, 'stock_quantity': 50, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Gowardhan',
        'category_slug': 'oils-ghee',
        'description': 'गोवर्धन १००% शुद्ध गायीचे तूप. सुवर्ण पिवळा रंग आणि अस्सल सुगंध.',
        'image_url': '/products/gowardhan-ghee-200ml.jpg',
        'is_loose': False,
        'name': 'Gowardhan Pure Cow Ghee (200ml Pouch)',
        'name_hi': 'गोवर्धन शुद्ध गायीचे तूप (२०० मिली पाउच)',
        'variants': [{'mrp': 145.0, 'selling_price': 145.0, 'stock_quantity': 30, 'unit_size': '200ml Pouch'}]},
    {   'brand': 'Gowardhan',
        'category_slug': 'oils-ghee',
        'description': 'गोवर्धन शुद्ध गायीचे तूप ५०० मिली सोयीस्कर जार पॅक.',
        'image_url': '/products/gowardhan-ghee-500ml.jpg',
        'is_loose': False,
        'name': 'Gowardhan Pure Cow Ghee (500ml Jar)',
        'name_hi': 'गोवर्धन शुद्ध गायीचे तूप (५०० मिली जार)',
        'variants': [{'mrp': 360.0, 'selling_price': 360.0, 'stock_quantity': 25, 'unit_size': '500ml Jar'}]},
    {   'brand': 'Gowardhan',
        'category_slug': 'oils-ghee',
        'description': 'गोवर्धन शुद्ध गायीचे दाणेदार तूप १ किलो पॅक.',
        'image_url': '/products/gowardhan-ghee-1kg.jpg',
        'is_loose': False,
        'name': 'Gowardhan Pure Cow Ghee (1kg Tin / Jar)',
        'name_hi': 'गोवर्धन शुद्ध गायीचे तूप (१ किलो टिन / जार)',
        'variants': [{'mrp': 695.0, 'selling_price': 695.0, 'stock_quantity': 20, 'unit_size': '1kg Tin'}]},
    {   'brand': 'Amul',
        'category_slug': 'oils-ghee',
        'description': 'अमूल १००% शुद्ध दाणेदार तूप. भारतातील घराघरांचा विश्वास.',
        'image_url': '/products/amul-ghee-pouch-1l.jpg',
        'is_loose': False,
        'name': 'Amul Pure Ghee (1L Refill Pouch)',
        'name_hi': 'अमूल शुद्ध तूप (१ लिटर रीफिल पाउच)',
        'variants': [{'mrp': 610.0, 'selling_price': 610.0, 'stock_quantity': 30, 'unit_size': '1L Pouch'}]},
    {   'brand': 'Amul',
        'category_slug': 'oils-ghee',
        'description': 'अमूल शुद्ध तूप १ लिटर धातूचा डबा/जार. साठवणीसाठी सुरक्षित आणि ताजे.',
        'image_url': '/products/amul-ghee-jar-1l.jpg',
        'is_loose': False,
        'name': 'Amul Pure Ghee (1L Tin / Jar)',
        'name_hi': 'अमूल शुद्ध तूप (१ लिटर डबा / जार)',
        'variants': [{'mrp': 630.0, 'selling_price': 630.0, 'stock_quantity': 25, 'unit_size': '1L Tin'}]},
    {   'brand': 'Dalda',
        'category_slug': 'oils-ghee',
        'description': 'अस्सल डालडा वनस्पती. खस्ता समोसे, कचोरी व दिवाळी फराळासाठी उत्तम.',
        'image_url': '/products/dalda-vanaspati-1kg.jpg',
        'is_loose': False,
        'name': 'Dalda Vanaspati Ghee (1kg Pouch)',
        'name_hi': 'डालडा वनस्पती तूप (१ किलो पाउच)',
        'variants': [   {'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 40, 'unit_size': '500g'},
                        {'mrp': 145.0, 'selling_price': 145.0, 'stock_quantity': 35, 'unit_size': '1kg'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'एव्हरेस्ट गरम मसाला. १३ मसाल्यांचे परिपूर्ण मिश्रण जेवणाचा स्वाद द्विगुणित करते.',
        'image_url': '/products/everest-garam-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Garam Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट गरम मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 92.0, 'selling_price': 92.0, 'stock_quantity': 60, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'एव्हरेस्ट गरम मसाला ५ रुपयांची छोटी सोयीस्कर पुडी.',
        'image_url': '/products/everest-garam-masala-5rs.jpg',
        'is_loose': False,
        'name': 'Everest Garam Masala (₹5 Pouch)',
        'name_hi': 'एव्हरेस्ट गरम मसाला (५ रुपये पुडी)',
        'variants': [{'mrp': 5.0, 'selling_price': 5.0, 'stock_quantity': 200, 'unit_size': '₹5 Pouch'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'एव्हरेस्ट चिकन मसाला. झणझणीत रस्सा आणि सुका चिकनसाठी अस्सल मसालेदार चव.',
        'image_url': '/products/everest-chicken-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Chicken Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट चिकन मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 88.0, 'selling_price': 88.0, 'stock_quantity': 50, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'एव्हरेस्ट चिकन मसाला ५ रुपयांची छोटी पुडी.',
        'image_url': '/products/everest-chicken-masala-5rs.jpg',
        'is_loose': False,
        'name': 'Everest Chicken Masala (₹5 Pouch)',
        'name_hi': 'एव्हरेस्ट चिकन मसाला (५ रुपये पुडी)',
        'variants': [{'mrp': 5.0, 'selling_price': 5.0, 'stock_quantity': 200, 'unit_size': '₹5 Pouch'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'मुंबई स्पेशल चौपाटी स्टाईल चवदार पावभाजी बनवण्यासाठी एव्हरेस्ट पावभाजी मसाला.',
        'image_url': '/products/everest-pav-bhaji-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Pav Bhaji Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट पावभाजी मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 82.0, 'selling_price': 82.0, 'stock_quantity': 60, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'पंजाबी स्टाईल पिंडी छोले बनवण्यासाठी खास एव्हरेस्ट छोले मसाला.',
        'image_url': '/products/everest-chhole-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Chhole Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट छोले मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 82.0, 'selling_price': 82.0, 'stock_quantity': 50, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'अस्सल उडुपि स्टाईल सांबारासाठी सुवासिक एव्हरेस्ट सांबार मसाला.',
        'image_url': '/products/everest-sambhar-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Sambhar Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट सांबार मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 80.0, 'selling_price': 80.0, 'stock_quantity': 50, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'सर्व प्रकारच्या भाज्यांमध्ये शाही स्वाद आणणारा एव्हरेस्ट किचन किंग मसाला.',
        'image_url': '/products/everest-kitchen-king-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Kitchen King Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट किचन किंग मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 60, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'सलाड, फळे व चाटवर भुरभुरण्यासाठी आंबट-गोड-खारट चटपटीत चाट मसाला.',
        'image_url': '/products/everest-chaat-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Chaat Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट चाट मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 50, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'रोजच्या साध्या भाज्यांना अप्रतिम चव देणारा एव्हरेस्ट भाजी मसाला.',
        'image_url': '/products/everest-sabji-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Sabji Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट भाजी मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 65.0, 'selling_price': 65.0, 'stock_quantity': 50, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'दम बिर्याणीसाठी केशर व खड्या मसाल्यांचे शाही मिश्रण.',
        'image_url': '/products/everest-shahi-biryani-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Shahi Biryani Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट शाही बिर्याणी मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 40, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'हॉटेलसारखी शाही पनीर व पनीर बटर मसाला बनवण्यासाठी खास मसाला.',
        'image_url': '/products/everest-shahi-paneer-masala-100g.jpg',
        'is_loose': False,
        'name': 'Everest Shahi Paneer Masala (100g Box)',
        'name_hi': 'एव्हरेस्ट शाही पनीर मसाला (१०० ग्रॅम बॉक्स)',
        'variants': [{'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 40, 'unit_size': '100g Box'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'एव्हरेस्ट शुद्ध हळद पावडर ५०० ग्रॅम सोयीस्कर प्लास्टिक जार पॅक.',
        'image_url': '/products/everest-turmeric-jar-500g.jpg',
        'is_loose': False,
        'name': 'Everest Turmeric Powder Jar (500g Jar)',
        'name_hi': 'एव्हरेस्ट हळद पावडर जार (५०० ग्रॅम)',
        'variants': [{'mrp': 180.0, 'selling_price': 180.0, 'stock_quantity': 30, 'unit_size': '500g Jar'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'उच्च करक्युमिनयुक्त एव्हरेस्ट शुद्ध हळद पावडर.',
        'image_url': '/products/everest-haldi-pack-100g.jpg',
        'is_loose': False,
        'name': 'Everest Turmeric / Haldi Powder (100g Pack)',
        'name_hi': 'एव्हरेस्ट हळद पावडर (१०० ग्रॅम / २०० ग्रॅम)',
        'variants': [   {'mrp': 38.0, 'selling_price': 38.0, 'stock_quantity': 60, 'unit_size': '100g Pack'},
                        {'mrp': 74.0, 'selling_price': 74.0, 'stock_quantity': 40, 'unit_size': '200g Pack'}]},
    {   'brand': 'Suhana',
        'category_slug': 'spices-masalas',
        'description': 'सुहाना अस्सल निवडलेली हळद पावडर.',
        'image_url': '/products/suhana-haldi-pack-100g.jpg',
        'is_loose': False,
        'name': 'Suhana Turmeric Powder (100g Pack)',
        'name_hi': 'सुहाना हळद पावडर (१०० ग्रॅम)',
        'variants': [{'mrp': 36.0, 'selling_price': 36.0, 'stock_quantity': 50, 'unit_size': '100g Pack'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'राजापुरी हळकुंडातून दळलेली अस्सल पिवळीधमक हळद. कोणतीही भेसळ नाही.',
        'image_url': '/products/pure-haldi-powder-loose.jpg',
        'is_loose': True,
        'name': 'Pure Haldi Powder (Loose Mandi Turmeric)',
        'name_hi': 'शुद्ध हळद पावडर (मोकळी अस्सल राजापुरी)',
        'variants': [   {'mrp': 25.0, 'selling_price': 25.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 120.0, 'selling_price': 120.0, 'stock_quantity': 40, 'unit_size': '500g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'बेडगी व गुंटूर मिरचीचे अस्सल मिश्रण. सुरेख लाल रंग आणि मध्यम तिखटपणा.',
        'image_url': '/products/pure-lal-mirch-loose.jpg',
        'is_loose': True,
        'name': 'Pure Lal Mirch Powder (Loose Red Chilli Powder)',
        'name_hi': 'शुद्ध लाल मिरची पावडर (तिखट मोकळी)',
        'variants': [   {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 170.0, 'selling_price': 170.0, 'stock_quantity': 40, 'unit_size': '500g'},
                        {'mrp': 330.0, 'selling_price': 330.0, 'stock_quantity': 30, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'हिरव्या ताज्या धन्यापासून बनवलेली ताजी धने पूड. रस्सा घट्ट व सुवासिक करण्यासाठी.',
        'image_url': '/products/dhaniya-powder-loose.jpg',
        'is_loose': True,
        'name': 'Dhaniya Powder (Loose Coriander Powder)',
        'name_hi': 'धने पावडर (मोकळी सुगंधित)',
        'variants': [   {'mrp': 25.0, 'selling_price': 25.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 120.0, 'selling_price': 120.0, 'stock_quantity': 40, 'unit_size': '500g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'स्वच्छ आणि निवडलेले अखंड जिरे. फोडणी आणि जिराराइससाठी सुगंधित.',
        'image_url': '/products/cumin-jeera-seeds.jpg',
        'is_loose': True,
        'name': 'Sabut Jeera (Cumin Seeds Loose Mandi)',
        'name_hi': 'अखंड जिरे (मोकळे व ₹१० पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 170.0, 'selling_price': 170.0, 'stock_quantity': 40, 'unit_size': '500g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'बारीक काळी मोहरी. खमंग फोडणी, सांबार व लोणच्यासाठी अतिशय आवश्यक.',
        'image_url': '/products/black-mustard-rai.jpg',
        'is_loose': True,
        'name': 'Kali Rai (Black Mustard Seeds Loose)',
        'name_hi': 'काळी मोहरी (मोकळी व ₹१० पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 15.0, 'selling_price': 15.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 70.0, 'selling_price': 70.0, 'stock_quantity': 40, 'unit_size': '500g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'सुवासिक अखंड धने. घरगुती गरम मसाला व भाज्यांच्या फोडणीसाठी.',
        'image_url': '/products/dhaniya-seeds-whole.jpg',
        'is_loose': True,
        'name': 'Sabut Dhaniya (Whole Coriander Seeds Loose)',
        'name_hi': 'अखे धने (मोकळे फोडणी व मसाला स्पेशल)',
        'variants': [   {'mrp': 18.0, 'selling_price': 18.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 42.0, 'selling_price': 42.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 80.0, 'selling_price': 80.0, 'stock_quantity': 40, 'unit_size': '500g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'गोडसर हिरवी बडीशेप. जेवणानंतर मुखवास म्हणून आणि मसाल्यांसाठी पाचक.',
        'image_url': '/products/badi-saunf-fennel.jpg',
        'is_loose': True,
        'name': 'Badi Saunf (Fennel Seeds Loose)',
        'name_hi': 'बडीशेप (मोकळी मुखवास व मसाला)',
        'variants': [   {'mrp': 25.0, 'selling_price': 25.0, 'stock_quantity': 80, 'unit_size': '100g'},
                        {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 120.0, 'selling_price': 120.0, 'stock_quantity': 40, 'unit_size': '500g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'मलबारची अस्सल काळी मिरी. तिखट, सुवासिक आणि औषधी गुणांनी युक्त.',
        'image_url': '/products/kali-mirch-pepper.jpg',
        'is_loose': True,
        'name': 'Sabut Kali Mirch (Black Pepper Loose Mandi)',
        'name_hi': 'काळी मिरी (अखंड मोकळी व ₹१० पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 60, 'unit_size': '50g'},
                        {'mrp': 105.0, 'selling_price': 105.0, 'stock_quantity': 50, 'unit_size': '100g'},
                        {'mrp': 250.0, 'selling_price': 250.0, 'stock_quantity': 30, 'unit_size': '250g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'गोडसर सुवासिक दालचिनीच्या काड्या. चहा, पुलाव व बिर्याणीसाठी उत्तम.',
        'image_url': '/products/dalchini-cinnamon.jpg',
        'is_loose': True,
        'name': 'Dalchini (Cinnamon Sticks Loose)',
        'name_hi': 'दालचिनी (अखंड काड्या मोकळी व ₹१० पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 60, 'unit_size': '50g'},
                        {'mrp': 70.0, 'selling_price': 70.0, 'stock_quantity': 40, 'unit_size': '100g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'सुवासिक हिरवी वेलची. चहा, शिरा, खीर आणि मोदकाच्या सारणासाठी खास.',
        'image_url': '/products/green-elaichi-small.jpg',
        'is_loose': True,
        'name': 'Chhoti Elaichi (Green Cardamom Loose)',
        'name_hi': 'हिरवी वेलची (मोकळी व ₹१०/₹२० पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 100, 'unit_size': '₹20 Pouch'},
                        {'mrp': 190.0, 'selling_price': 190.0, 'stock_quantity': 40, 'unit_size': '50g'},
                        {'mrp': 370.0, 'selling_price': 370.0, 'stock_quantity': 30, 'unit_size': '100g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'मसाल्याची मोठी काळी वेलची. बिर्याणी, पुलाव व छोलेसाठी विशिष्ट खमंग चव.',
        'image_url': '/products/black-cardamom-badi.jpg',
        'is_loose': True,
        'name': 'Badi Elaichi (Black Cardamom Loose)',
        'name_hi': 'काळी मोठी वेलची (मोकळी व ₹१० पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 40, 'unit_size': '50g'},
                        {'mrp': 180.0, 'selling_price': 180.0, 'stock_quantity': 30, 'unit_size': '100g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'ताराफूल / चक्रफूल. शाही पुलाव आणि गरम मसाल्यासाठी आवश्यक खडा मसाला.',
        'image_url': '/products/star-anise-chakra-phool.jpg',
        'is_loose': True,
        'name': 'Star Anise / Chakra Phool (Loose Mandi)',
        'name_hi': 'चक्रफूल (मोकळे व ₹१० पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 50, 'unit_size': '50g'},
                        {'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 30, 'unit_size': '100g'}]},
    {   'brand': 'Everest',
        'category_slug': 'spices-masalas',
        'description': 'एव्हरेस्ट वाळवलेली सुवासिक मेथी. पनीर भाजी व पराठ्यांवर चुरा करून घालण्यासाठी.',
        'image_url': '/products/everest-kasuri-methi-25g.jpg',
        'is_loose': False,
        'name': 'Everest Kasuri Methi (Fenugreek Leaves 25g Box)',
        'name_hi': 'एव्हरेस्ट कसुरी मेथी (२५ ग्रॅम बॉक्स)',
        'variants': [{'mrp': 26.0, 'selling_price': 26.0, 'stock_quantity': 50, 'unit_size': '25g Box'}]},
    {   'brand': 'Vandevi',
        'category_slug': 'spices-masalas',
        'description': 'वानदेवी पिवळा हिंग. डाळ व भाजीच्या खमंग फोडणीसाठी आणि पचनासाठी सर्वोत्तम.',
        'image_url': '/products/vandevi-hing-tub.jpg',
        'is_loose': False,
        'name': 'Vandevi Compounded Hing (Asafoetida 100g Tub)',
        'name_hi': 'वानदेवी हिंग डबी (५० ग्रॅम / १०० ग्रॅम)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 50, 'unit_size': '50g Tub'},
                        {'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 40, 'unit_size': '100g Tub'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'कडवट औषधी मेथी पावडर. पचन, मधुमेह नियंत्रण व लोणच्याच्या मसाल्यासाठी.',
        'image_url': '/products/methi-dana-powder.jpg',
        'is_loose': True,
        'name': 'Methi Dana Powder (Fenugreek Seed Powder Loose)',
        'name_hi': 'मेथी दाणा पावडर (मोकळी)',
        'variants': [   {'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 60, 'unit_size': '100g'},
                        {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 40, 'unit_size': '250g'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'तमालपत्र, लवंग, मिरी, दालचिनी, वेलची व चक्रफूल यांचे परिपूर्ण खडा मसाला मिश्रण.',
        'image_url': '/products/khada-garam-masala-mix.jpg',
        'is_loose': True,
        'name': 'Sabut Khada Garam Masala Mix (Loose Mandi)',
        'name_hi': 'अखंड खडा गरम मसाला मिक्स (मोकळा व पुडी)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'},
                        {'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 100, 'unit_size': '₹20 Pouch'},
                        {'mrp': 65.0, 'selling_price': 65.0, 'stock_quantity': 60, 'unit_size': '100g'},
                        {'mrp': 160.0, 'selling_price': 160.0, 'stock_quantity': 40, 'unit_size': '250g'}]},
    {   'brand': 'Tata Salt',
        'category_slug': 'spices-masalas',
        'description': 'देश का नमक टाटा सॉल्ट. व्हॅक्यूम बाष्पीभवन पद्धतीने शुद्ध केलेले आयोडीनयुक्त मीठ.',
        'image_url': '/products/tata-salt-1kg.jpg',
        'is_loose': False,
        'name': 'Tata Salt Vacuum Evaporated Iodized Salt (1kg Pack)',
        'name_hi': 'टाटा मीठ (१ किलो पॅक देश का नमक)',
        'variants': [{'mrp': 28.0, 'selling_price': 28.0, 'stock_quantity': 100, 'unit_size': '1kg Pack'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'पाचक काळे मीठ. रायता, ताक, पाणीपुरी व चाटमध्ये विशिष्ट चवीसाठी.',
        'image_url': '/products/black-salt-kala-namak.jpg',
        'is_loose': True,
        'name': 'Kala Namak (Black Salt Powder Loose)',
        'name_hi': 'काळे मीठ पावडर (मोकळे पाचक)',
        'variants': [   {'mrp': 15.0, 'selling_price': 15.0, 'stock_quantity': 80, 'unit_size': '200g'},
                        {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 60, 'unit_size': '500g'}]},
    {   'brand': 'Himalayan',
        'category_slug': 'spices-masalas',
        'description': 'नैसर्गिक खनिजांनी युक्त गुलाबी सैंधव मीठ. रक्तदाब नियंत्रण व निरोगी आहारासाठी उत्तम.',
        'image_url': '/products/himalayan-pink-salt-1kg.jpg',
        'is_loose': False,
        'name': 'Himalayan Pink Rock Salt Powder (Sendha Namak 1kg Pouch)',
        'name_hi': 'हिमालयन गुलाबी सैंधव मीठ (१ किलो पाउच)',
        'variants': [{'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 40, 'unit_size': '1kg Pouch'}]},
    {   'brand': 'Mandi Spices',
        'category_slug': 'spices-masalas',
        'description': 'उपवासाचे अखंड खडे सैंधव मीठ. १००% शुद्ध आणि उपवासाच्या फराळासाठी आवश्यक.',
        'image_url': '/products/sendha-namak-khadak.jpg',
        'is_loose': True,
        'name': 'Sendha Namak Khadak (Rock Salt Crystals Loose)',
        'name_hi': 'सैंधव मीठ खडक / खडे (मोकळे उपवास स्पेशल)',
        'variants': [   {'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 38.0, 'selling_price': 38.0, 'stock_quantity': 50, 'unit_size': '500g'},
                        {'mrp': 70.0, 'selling_price': 70.0, 'stock_quantity': 40, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'sugar-jaggery',
        'description': 'स्वच्छ पांढरी शुभ्र दाणेदार साखर. सल्फरमुक्त, चहा व गोड पदार्थांसाठी.',
        'image_url': '/products/sugar-clean-loose.jpg',
        'is_loose': True,
        'name': 'Madhur Clean Sugar (Loose Mandi)',
        'name_hi': 'साखर स्वच्छ (मोकळी व ५ किलो घाऊक)',
        'variants': [   {'mrp': 44.0, 'selling_price': 44.0, 'stock_quantity': 150, 'unit_size': '1kg'},
                        {'mrp': 88.0, 'selling_price': 88.0, 'stock_quantity': 80, 'unit_size': '2kg'},
                        {'mrp': 220.0, 'selling_price': 218.0, 'stock_quantity': 50, 'unit_size': '5kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'sugar-jaggery',
        'description': 'अस्सल धाग्याची आयुर्वेदिक खडीसाखर. घशाची खवखव, बडीशेपसोबत मुखवास व पूजा साहित्यासाठी.',
        'image_url': '/products/dhaga-mishri-loose.jpg',
        'is_loose': True,
        'name': 'Dhaga Mishri / Rock Sugar Crystals (Loose)',
        'name_hi': 'धागा खडीसाखर (मोकळी शुद्ध)',
        'variants': [   {'mrp': 30.0, 'selling_price': 30.0, 'stock_quantity': 60, 'unit_size': '250g'},
                        {'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 50, 'unit_size': '500g'},
                        {'mrp': 105.0, 'selling_price': 105.0, 'stock_quantity': 40, 'unit_size': '1kg'}]},
    {   'brand': 'Mandi Staples',
        'category_slug': 'sugar-jaggery',
        'description': 'देशी पिवळा गूळ. मऊ, गोड आणि चहा, लाडू व पुरणासाठी उत्कृष्ट.',
        'image_url': '/products/desi-yellow-jaggery.jpg',
        'is_loose': True,
        'name': 'Desi Yellow Jaggery / Pila Gud (Loose Mandi)',
        'name_hi': 'देशी पिवळा गूळ (मोकळा गोड)',
        'variants': [   {'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 80, 'unit_size': '500g'},
                        {'mrp': 68.0, 'selling_price': 68.0, 'stock_quantity': 80, 'unit_size': '1kg'}]},
    {   'brand': 'Kolhapuri',
        'category_slug': 'sugar-jaggery',
        'description': 'अस्सल कोल्हापुरी शुद्ध गूळ ढेप. सेंद्रिय, नैसर्गिक गोडवा आणि चहा न फाटणारा गूळ.',
        'image_url': '/products/kolhapuri-golden-jaggery-1kg.jpg',
        'is_loose': False,
        'name': 'Kolhapuri Golden Jaggery Block (1kg Block)',
        'name_hi': 'कोल्हापुरी गोल्डन गूळ ढेप (१ किलो)',
        'variants': [{'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 50, 'unit_size': '1kg Block'}]},
    {   'brand': 'Society Tea',
        'category_slug': 'tea-beverages',
        'description': 'सोसायटी प्रीमियम चहा. मुंबईकरांची सकाळ ताजीतवानी करणारा कडक चहा.',
        'image_url': '/products/society-tea-pack.jpg',
        'is_loose': False,
        'name': 'Society Tea Premium CTC Blend (250g / 500g)',
        'name_hi': 'सोसायटी चहा (२५० ग्रॅम / ५०० ग्रॅम)',
        'variants': [   {'mrp': 150.0, 'selling_price': 150.0, 'stock_quantity': 50, 'unit_size': '250g Pack'},
                        {'mrp': 295.0, 'selling_price': 295.0, 'stock_quantity': 30, 'unit_size': '500g Pack'}]},
    {   'brand': 'Tata Tea',
        'category_slug': 'tea-beverages',
        'description': 'टाटा टी अग्नी. कडक चव, जास्त कप आणि खिशाला परवडणारा चहा.',
        'image_url': '/products/tata-tea-agni-pack.jpg',
        'is_loose': False,
        'name': 'Tata Tea Agni (250g / 500g)',
        'name_hi': 'टाटा टी अग्नी (२५० ग्रॅम / ५०० ग्रॅम)',
        'variants': [   {'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 60, 'unit_size': '250g Pack'},
                        {'mrp': 145.0, 'selling_price': 145.0, 'stock_quantity': 40, 'unit_size': '500g Pack'}]},
    {   'brand': 'Brooke Bond',
        'category_slug': 'tea-beverages',
        'description': '५ आयुर्वेदिक घटकांनी युक्त - तुळस, आलं, वेलची, अश्वगंधा व मुलेठी.',
        'image_url': '/products/red-label-natural-care-pack.jpg',
        'is_loose': False,
        'name': 'Brooke Bond Red Label Natural Care Tea (250g / 500g)',
        'name_hi': 'रेड लेबल नॅचरल केअर चहा (२५० ग्रॅम / ५०० ग्रॅम)',
        'variants': [   {'mrp': 160.0, 'selling_price': 160.0, 'stock_quantity': 40, 'unit_size': '250g Pack'},
                        {'mrp': 315.0, 'selling_price': 315.0, 'stock_quantity': 25, 'unit_size': '500g Pack'}]},
    {   'brand': 'Nescafe',
        'category_slug': 'tea-beverages',
        'description': 'नेस्कॅफे क्लासिक इन्स्टंट कॉफी १ रुपयाची सोयीस्कर पुडी.',
        'image_url': '/products/nescafe-sachet-1rs.jpg',
        'is_loose': False,
        'name': 'Nescafé Classic Instant Coffee (₹1 / ₹2 Sachet)',
        'name_hi': 'नेस्कॅफे क्लासिक इन्स्टंट कॉफी (१ रुपया / २ रुपये पुडी)',
        'variants': [   {'mrp': 1.0, 'selling_price': 1.0, 'stock_quantity': 250, 'unit_size': '₹1 Sachet'},
                        {'mrp': 2.0, 'selling_price': 2.0, 'stock_quantity': 200, 'unit_size': '₹2 Sachet'}]},
    {   'brand': 'Nescafe',
        'category_slug': 'tea-beverages',
        'description': 'नेस्कॅफे क्लासिक १००% शुद्ध कॉफी ५० ग्रॅम प्रीमियम काचेची बरणी.',
        'image_url': '/products/nescafe-glass-jar-50g.jpg',
        'is_loose': False,
        'name': 'Nescafé Classic Instant Coffee (50g Glass Jar)',
        'name_hi': 'नेस्कॅफे क्लासिक इन्स्टंट कॉफी (५० ग्रॅम काचेची बरणी)',
        'variants': [{'mrp': 195.0, 'selling_price': 195.0, 'stock_quantity': 30, 'unit_size': '50g Glass Jar'}]},
    {   'brand': 'Bru',
        'category_slug': 'tea-beverages',
        'description': 'ब्रू इन्स्टंट कॉफी २ रुपयांची सुलभ पुडी. कॉफी व चिकोरीचे उत्तम मिश्रण.',
        'image_url': '/products/bru-instant-coffee-sachet.jpg',
        'is_loose': False,
        'name': 'Bru Instant Coffee (₹2 Sachet)',
        'name_hi': 'ब्रू इन्स्टंट कॉफी (२ रुपये पुडी)',
        'variants': [{'mrp': 2.0, 'selling_price': 2.0, 'stock_quantity': 200, 'unit_size': '₹2 Sachet'}]},
    {   'brand': 'Parle',
        'category_slug': 'biscuits-bakery',
        'description': 'भारताचे लाडके पारले-जी बिस्किट. चहासोबत बुडवून खाण्यासाठी सर्वांचे आवडते.',
        'image_url': '/products/parle-g-biscuits.jpg',
        'is_loose': False,
        'name': 'Parle-G Original Gluco Biscuits (₹10 Pack)',
        'name_hi': 'पारले-जी ग्लुको बिस्किटे (१० रुपये पॅक)',
        'variants': [   {'mrp': 5.0, 'selling_price': 5.0, 'stock_quantity': 100, 'unit_size': '₹5 Mini Pack'},
                        {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 100, 'unit_size': '₹10 Pack'}]},
    {   'brand': 'Britannia',
        'category_slug': 'biscuits-bakery',
        'description': 'ब्रिटानिया गुड डे रिच बटर कुकीज. प्रत्येक घासात बटरचा समृद्ध स्वाद.',
        'image_url': '/products/good-day-butter-cookies.jpg',
        'is_loose': False,
        'name': 'Britannia Good Day Butter Cookies (₹10 / ₹30)',
        'name_hi': 'ब्रिटानिया गुड डे बटर कुकीज (१० रुपये / ३० रुपये)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 80, 'unit_size': '₹10 Pack'},
                        {'mrp': 30.0, 'selling_price': 30.0, 'stock_quantity': 40, 'unit_size': '₹30 Pack'}]},
    {   'brand': 'Britannia',
        'category_slug': 'biscuits-bakery',
        'description': 'ब्रिटानिया गुड डे क्रंची काजू कुकीज. खऱ्याखुऱ्या काजूच्या तुकड्यांनी भरलेले.',
        'image_url': '/products/good-day-cashew-cookies.jpg',
        'is_loose': False,
        'name': 'Britannia Good Day Cashew Cookies (₹10 / ₹30)',
        'name_hi': 'ब्रिटानिया गुड डे काजू कुकीज (१० रुपये / ३० रुपये)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 80, 'unit_size': '₹10 Pack'},
                        {'mrp': 30.0, 'selling_price': 30.0, 'stock_quantity': 40, 'unit_size': '₹30 Pack'}]},
    {   'brand': 'Cadbury',
        'category_slug': 'biscuits-bakery',
        'description': 'ओरियो क्रंची चॉकलेट कुकीज व्हॅनिला क्रीमसह. ट्विस्ट, लिक, डंक!',
        'image_url': '/products/cadbury-oreo-10rs.jpg',
        'is_loose': False,
        'name': 'Cadbury Oreo Vanilla Cream Biscuits (₹10 Pack)',
        'name_hi': 'कॅडबरी ओरियो व्हॅनिला क्रीम बिस्किटे (१० रुपये पॅक)',
        'variants': [   {'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 80, 'unit_size': '₹10 Pack'},
                        {'mrp': 30.0, 'selling_price': 30.0, 'stock_quantity': 40, 'unit_size': '₹30 Pack'}]},
    {   'brand': 'Lijjat',
        'category_slug': 'biscuits-bakery',
        'description': 'अस्सल लिज्जत उडीद मिरी पापड. भाजून किंवा तळून खाण्यासाठी खमंग कुरकुरीत.',
        'image_url': '/products/lijjat-udad-papad-200g.jpg',
        'is_loose': False,
        'name': 'Shri Mahila Gruha Udyog Lijjat Udad Papad (200g Pack)',
        'name_hi': 'लिज्जत उडीद पापड (२०० ग्रॅम पॅक)',
        'variants': [{'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 50, 'unit_size': '200g Pack'}]},
    {   'brand': 'Siddhivinayak',
        'category_slug': 'biscuits-bakery',
        'description': 'आंबा, लिंबू, गाजर व हिरव्या मिरचीचे चटपटीत तेलयुक्त पारंपरिक लोणचे.',
        'image_url': '/products/siddhivinayak-mixed-pickle-400g.jpg',
        'is_loose': False,
        'name': 'Shree Siddhivinayak Special Mixed Pickle (400g Jar)',
        'name_hi': 'सिद्धिविनायक स्पेशल मिक्स लोणचे (४०० ग्रॅम)',
        'variants': [{'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 40, 'unit_size': '400g Jar'}]},
    {   'brand': 'Mandi Pickles',
        'category_slug': 'biscuits-bakery',
        'description': 'राईच्या तेलातील आणि मेथीच्या मसाल्यातील अस्सल गावरान आंब्याचे लोणचे.',
        'image_url': '/products/desi-mango-pickle-500g.jpg',
        'is_loose': False,
        'name': 'Traditional Desi Mango Pickle (Aam Ka Achar 500g Jar)',
        'name_hi': 'पारंपारिक गावरान आंब्याचे लोणचे (५०० ग्रॅम बरणी)',
        'variants': [{'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 40, 'unit_size': '500g Jar'}]},
    {   'brand': 'Mandi Pickles',
        'category_slug': 'biscuits-bakery',
        'description': 'कागदी लिंबाचे चवदार आणि पाचक पारंपरिक लोणचे.',
        'image_url': '/products/desi-lemon-pickle-500g.jpg',
        'is_loose': False,
        'name': 'Traditional Tangy Lemon Pickle (Nimbu Achar 500g Jar)',
        'name_hi': 'पारंपारिक आंबट-गोड लिंबाचे लोणचे (५०० ग्रॅम बरणी)',
        'variants': [{'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 40, 'unit_size': '500g Jar'}]},
    {   'brand': 'Sprite',
        'category_slug': 'cold-drinks',
        'description': 'थंडगार रिफ्रेशिंग स्प्राइट लेमन-लाईम फ्लेवर. क्लिअर है!',
        'image_url': '/products/sprite-250ml-bottle.jpg',
        'is_loose': False,
        'name': 'Sprite Lemon Lime Cold Drink (250ml Pet Bottle)',
        'name_hi': 'स्प्राइट शीतपेय (२५० मिली २० रुपये बाटली)',
        'variants': [{'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 60, 'unit_size': '250ml Bottle'}]},
    {   'brand': 'Coca-Cola',
        'category_slug': 'cold-drinks',
        'description': 'अस्सल थंडा कोका-कोला २५० मिली चिल्ड पेट बॉटल.',
        'image_url': '/products/coca-cola-250ml-bottle.jpg',
        'is_loose': False,
        'name': 'Coca-Cola Soft Drink (250ml Pet Bottle)',
        'name_hi': 'कोका-कोला शीतपेय (२५० मिली २० रुपये बाटली)',
        'variants': [{'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 60, 'unit_size': '250ml Bottle'}]},
    {   'brand': 'Campa',
        'category_slug': 'cold-drinks',
        'description': 'द ग्रेट इंडियन टेस्ट - कंपा कोला १० रुपयांची चिल्ड बाटली.',
        'image_url': '/products/campa-cola-200ml-bottle.jpg',
        'is_loose': False,
        'name': 'Campa Cola (200ml Pet Bottle)',
        'name_hi': 'कंपा कोला शीतपेय (२०० मिली १० रुपये बाटली)',
        'variants': [{'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 80, 'unit_size': '200ml Bottle'}]},
    {   'brand': 'Fena',
        'category_slug': 'household-cleaning',
        'description': 'फेना सुपरवॉश कपड्याचा साबण. हट्टी मळ काढून पांढरे कपडे लखलखीत करतो.',
        'image_url': '/products/fena-superwash-bar.jpg',
        'is_loose': False,
        'name': 'Fena Superwash Plus Detergent Soap Bar',
        'name_hi': 'फेना सुपरवॉश प्लस कपड्याचा साबण',
        'variants': [{'mrp': 15.0, 'selling_price': 15.0, 'stock_quantity': 80, 'unit_size': '200g Bar'}]},
    {   'brand': 'Rin',
        'category_slug': 'household-cleaning',
        'description': 'रिन बार. कपड्यांना देतो दुप्पट चमक आणि ताजेतवाने सुगंध.',
        'image_url': '/products/rin-detergent-bar-10rs.jpg',
        'is_loose': False,
        'name': 'Rin Detergent Soap Bar (₹10 Bar)',
        'name_hi': 'रिन डिटर्जंट बार (१० रुपये साबण)',
        'variants': [{'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 100, 'unit_size': '₹10 Bar'}]},
    {   'brand': 'Wheel',
        'category_slug': 'household-cleaning',
        'description': 'व्हील ग्रीन लेमन डिटर्जंट बार. लिंबाच्या शक्तीने स्वच्छ कपडे.',
        'image_url': '/products/wheel-lemon-soap-bar.jpg',
        'is_loose': False,
        'name': 'Active Wheel Green Lemon Detergent Bar',
        'name_hi': 'अॅक्टिव्ह व्हील ग्रीन लेमन कपड्याचा साबण',
        'variants': [{'mrp': 12.0, 'selling_price': 12.0, 'stock_quantity': 80, 'unit_size': '150g Bar'}]},
    {   'brand': 'Wheel',
        'category_slug': 'household-cleaning',
        'description': 'अॅक्टिव्ह व्हील २ इन १ वॉशिंग पावडर. मळ काढते आणि कपड्यांना देते सुगंध.',
        'image_url': '/products/wheel-detergent-powder-1kg.jpg',
        'is_loose': False,
        'name': 'Active Wheel 2 in 1 Detergent Powder (1kg Pack)',
        'name_hi': 'अॅक्टिव्ह व्हील २ इन १ वॉशिंग पावडर (१ किलो)',
        'variants': [{'mrp': 72.0, 'selling_price': 72.0, 'stock_quantity': 60, 'unit_size': '1kg Pack'}]},
    {   'brand': 'Tide',
        'category_slug': 'household-cleaning',
        'description': 'टाईड बार. कॉलर आणि कफचा मळ सहज काढणारा शक्तिशाली साबण.',
        'image_url': '/products/tide-detergent-bar.jpg',
        'is_loose': False,
        'name': 'Tide Detergent Bar (150g Bar)',
        'name_hi': 'टाईड डिटर्जंट बार (१५० ग्रॅम साबण)',
        'variants': [{'mrp': 15.0, 'selling_price': 15.0, 'stock_quantity': 80, 'unit_size': '150g Bar'}]},
    {   'brand': 'Tide',
        'category_slug': 'household-cleaning',
        'description': 'टाईड प्लस एक्स्ट्रा पॉवर १० रुपयांची छोटी सोयीस्कर पुडी.',
        'image_url': '/products/tide-powder-pouch-10rs.jpg',
        'is_loose': False,
        'name': 'Tide Plus Extra Power Detergent Powder (₹10 Pouch)',
        'name_hi': 'टाईड प्लस वॉशिंग पावडर (१० रुपये पुडी)',
        'variants': [{'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'}]},
    {   'brand': 'Tide',
        'category_slug': 'household-cleaning',
        'description': 'टाईड प्लस एक्स्ट्रा पॉवर १ किलो फॅमिली पॅक.',
        'image_url': '/products/tide-powder-1kg.jpg',
        'is_loose': False,
        'name': 'Tide Plus Extra Power Detergent Powder (1kg Pack)',
        'name_hi': 'टाईड प्लस एक्स्ट्रा पॉवर वॉशिंग पावडर (१ किलो)',
        'variants': [{'mrp': 135.0, 'selling_price': 135.0, 'stock_quantity': 50, 'unit_size': '1kg Pack'}]},
    {   'brand': 'Surf Excel',
        'category_slug': 'household-cleaning',
        'description': 'सर्फ एक्सेल क्विक वॉश १० रुपयांची पुडी. दाग अच्छे हैं!',
        'image_url': '/products/surf-excel-pouch-10rs.jpg',
        'is_loose': False,
        'name': 'Surf Excel Quick Wash Detergent Powder (₹10 Pouch)',
        'name_hi': 'सर्फ एक्सेल क्विक वॉश पावडर (१० रुपये पुडी)',
        'variants': [{'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Pouch'}]},
    {   'brand': 'Surf Excel',
        'category_slug': 'household-cleaning',
        'description': 'सर्फ एक्सेल इझी वॉश १ किलो. हट्टी डागांवर प्रभावी स्वच्छता.',
        'image_url': '/products/surf-excel-easy-wash-1kg.jpg',
        'is_loose': False,
        'name': 'Surf Excel Easy Wash Detergent Powder (1kg Pack)',
        'name_hi': 'सर्फ एक्सेल इझी वॉश डिटर्जंट पावडर (१ किलो)',
        'variants': [{'mrp': 150.0, 'selling_price': 150.0, 'stock_quantity': 50, 'unit_size': '1kg Pack'}]},
    {   'brand': 'Surf Excel',
        'category_slug': 'household-cleaning',
        'description': 'वॉशिंग मशीनसाठी खास सर्फ एक्सेल मॅटिक लिक्विड. मशीनमध्ये १००% विरघळते.',
        'image_url': '/products/surf-excel-matic-liquid-1l.jpg',
        'is_loose': False,
        'name': 'Surf Excel Matic Front & Top Load Liquid Detergent (1L Bottle)',
        'name_hi': 'सर्फ एक्सेल मॅटिक लिक्विड डिटर्जंट (१ लिटर)',
        'variants': [   {'mrp': 130.0, 'selling_price': 130.0, 'stock_quantity': 30, 'unit_size': '500ml Bottle'},
                        {'mrp': 240.0, 'selling_price': 240.0, 'stock_quantity': 25, 'unit_size': '1L Bottle'}]},
    {   'brand': 'Comfort',
        'category_slug': 'household-cleaning',
        'description': 'कपड्यांना मऊपणा आणि १४ दिवस टिकणारा सुवास देणारा कंफर्ट ४ रुपयांचा सॅशे.',
        'image_url': '/products/comfort-conditioner-sachet-4rs.jpg',
        'is_loose': False,
        'name': 'Comfort After Wash Fabric Conditioner (₹4 Pouch)',
        'name_hi': 'कंफर्ट फॅब्रिक कंडिशनर (४ रुपये सॅशे)',
        'variants': [{'mrp': 4.0, 'selling_price': 4.0, 'stock_quantity': 200, 'unit_size': '₹4 Pouch'}]},
    {   'brand': 'Comfort',
        'category_slug': 'household-cleaning',
        'description': 'कंफर्ट मॉर्निंग फ्रेश निळा ८६० मिली बाटली. कपड्यांचे धागे मऊ ठेवतो.',
        'image_url': '/products/comfort-morning-fresh-blue-860ml.jpg',
        'is_loose': False,
        'name': 'Comfort Morning Fresh Fabric Conditioner Blue (860ml Bottle)',
        'name_hi': 'कंफर्ट मॉर्निंग फ्रेश फॅब्रिक कंडिशनर (८६० मिली निळा)',
        'variants': [   {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 30, 'unit_size': '220ml Bottle'},
                        {'mrp': 220.0, 'selling_price': 220.0, 'stock_quantity': 20, 'unit_size': '860ml Bottle'}]},
    {   'brand': 'Comfort',
        'category_slug': 'household-cleaning',
        'description': 'कंफर्ट लिली फ्रेश गुलाबी ८६० मिली बाटली. सुवासिक फुलांचा सुगंध.',
        'image_url': '/products/comfort-lily-fresh-pink-860ml.jpg',
        'is_loose': False,
        'name': 'Comfort Lily Fresh Fabric Conditioner Pink (860ml Bottle)',
        'name_hi': 'कंफर्ट लिली फ्रेश फॅब्रिक कंडिशनर (८६० मिली गुलाबी)',
        'variants': [   {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 30, 'unit_size': '220ml Bottle'},
                        {'mrp': 220.0, 'selling_price': 220.0, 'stock_quantity': 20, 'unit_size': '860ml Bottle'}]},
    {   'brand': 'Vim',
        'category_slug': 'household-cleaning',
        'description': 'विम डिशवॉश बार ५ रुपयांचा छोटा साबण. लिंबाच्या शक्तीने तेलकट भांडी स्वच्छ.',
        'image_url': '/products/vim-dishwash-bar-5rs.jpg',
        'is_loose': False,
        'name': 'Vim Dishwash Bar with Lemon (₹5 Mini Bar)',
        'name_hi': 'विम डिशवॉश बार (५ रुपये छोटा साबण)',
        'variants': [{'mrp': 5.0, 'selling_price': 5.0, 'stock_quantity': 200, 'unit_size': '₹5 Bar'}]},
    {   'brand': 'Vim',
        'category_slug': 'household-cleaning',
        'description': 'विम डिशवॉश बार १० रुपयांचा लोकप्रिय साबण.',
        'image_url': '/products/vim-dishwash-bar-10rs.jpg',
        'is_loose': False,
        'name': 'Vim Dishwash Bar with Lemon (₹10 Bar)',
        'name_hi': 'विम डिशवॉश बार (१० रुपये साबण)',
        'variants': [{'mrp': 10.0, 'selling_price': 10.0, 'stock_quantity': 150, 'unit_size': '₹10 Bar'}]},
    {   'brand': 'Vim',
        'category_slug': 'household-cleaning',
        'description': 'विम जेल लिंबू १२० मिली. फक्त १ चमचा विम जेल सिंकभर भांड्यांसाठी पुरेसा.',
        'image_url': '/products/vim-dishwash-gel-120ml.jpg',
        'is_loose': False,
        'name': 'Vim Dishwash Liquid Gel Lemon (120ml Bottle)',
        'name_hi': 'विम डिशवॉश लिक्विड जेल (१२० मिली बाटली)',
        'variants': [{'mrp': 30.0, 'selling_price': 30.0, 'stock_quantity': 50, 'unit_size': '120ml Bottle'}]},
    {   'brand': 'Vim',
        'category_slug': 'household-cleaning',
        'description': 'विम डिशवॉश लिक्विड जेल २५० मिली बाटली. भांड्यांवर पांढरे डाग पडू देत नाही.',
        'image_url': '/products/vim-dishwash-gel-250ml.jpg',
        'is_loose': False,
        'name': 'Vim Dishwash Liquid Gel Lemon (250ml / 500ml Bottle)',
        'name_hi': 'विम डिशवॉश जेल लिंबू (२५० मिली / ५०० मिली बाटली)',
        'variants': [   {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 40, 'unit_size': '250ml Bottle'},
                        {'mrp': 115.0, 'selling_price': 115.0, 'stock_quantity': 25, 'unit_size': '500ml Bottle'}]},
    {   'brand': 'Exo',
        'category_slug': 'household-cleaning',
        'description': 'एक्सो अँटी-बॅक्टेरियल गोल डिशवॉश बार टबसह. पाणी साचून साबण वाया जात नाही.',
        'image_url': '/products/exo-round-dishwash-bar.jpg',
        'is_loose': False,
        'name': 'Exo Touch & Shine Round Dishwash Bar (250g Tub)',
        'name_hi': 'एक्सो टच अँड शाइन डिशवॉश बार (२५० ग्रॅम गोल टब)',
        'variants': [{'mrp': 32.0, 'selling_price': 32.0, 'stock_quantity': 50, 'unit_size': '250g Tub'}]},
    {   'brand': 'Harpic',
        'category_slug': 'household-cleaning',
        'description': 'हार्पिक १० पट जास्त मळ आणि पिवळे डाग काढणारा नंबर १ टॉयलेट क्लिनर.',
        'image_url': '/products/harpic-toilet-cleaner-blue.jpg',
        'is_loose': False,
        'name': 'Harpic Power Plus Toilet Cleaner Blue (500ml / 1L Bottle)',
        'name_hi': 'हार्पिक पॉवर प्लस टॉयलेट क्लिनर (५०० मिली निळा)',
        'variants': [   {'mrp': 99.0, 'selling_price': 99.0, 'stock_quantity': 40, 'unit_size': '500ml Bottle'},
                        {'mrp': 195.0, 'selling_price': 195.0, 'stock_quantity': 25, 'unit_size': '1L Bottle'}]},
    {   'brand': 'Harpic',
        'category_slug': 'household-cleaning',
        'description': 'हार्पिक रेड बाथरूम क्लिनर. टाईल्स, बेसिन आणि नळ लखलखीत स्वच्छ करतो.',
        'image_url': '/products/harpic-bathroom-cleaner-red.jpg',
        'is_loose': False,
        'name': 'Harpic Bathroom Cleaner Red Floral (500ml Bottle)',
        'name_hi': 'हार्पिक बाथरूम क्लिनर (५०० मिली लाल बाटली)',
        'variants': [{'mrp': 99.0, 'selling_price': 99.0, 'stock_quantity': 35, 'unit_size': '500ml Bottle'}]},
    {   'brand': 'Sunny',
        'category_slug': 'household-cleaning',
        'description': 'सन्नी हर्बल नैसर्गिक पाइन तेलाचे फिनाइल. फरशीवरील जंतू मारते आणि ताजा सुगंध देते.',
        'image_url': '/products/sunny-pine-floor-cleaner-1l.jpg',
        'is_loose': False,
        'name': 'Sunny Herbal Pine Floor Cleaner (1L Bottle)',
        'name_hi': 'सन्नी हर्बल पाइन फ्लोअर क्लिनर (१ लिटर फिनाइल)',
        'variants': [{'mrp': 75.0, 'selling_price': 75.0, 'stock_quantity': 40, 'unit_size': '1L Bottle'}]},
    {   'brand': 'Dettol',
        'category_slug': 'pooja-samagri',
        'description': 'डेटॉल ओरिजिनल जंतूनाशक साबण. १०० आजार पसरवणाऱ्या जंतूंपासून संरक्षण.',
        'image_url': '/products/dettol-original-soap-single.jpg',
        'is_loose': False,
        'name': 'Dettol Original Bathing Soap (75g Single Bar)',
        'name_hi': 'डेटॉल ओरिजिनल आंघोळीचा साबण (७५ ग्रॅम एक साबण)',
        'variants': [{'mrp': 40.0, 'selling_price': 40.0, 'stock_quantity': 80, 'unit_size': '75g Single Bar'}]},
    {   'brand': 'Dettol',
        'category_slug': 'pooja-samagri',
        'description': 'डेटॉल ओरिजिनल ४ साबणांचा सुपर सेव्हर फॅमिली पॅक.',
        'image_url': '/products/dettol-original-soap-pack4.jpg',
        'is_loose': False,
        'name': 'Dettol Original Bathing Soap (Pack of 4 x 75g)',
        'name_hi': 'डेटॉल ओरिजिनल साबण (४ साबणाचा कॉम्बो पॅक)',
        'variants': [{'mrp': 155.0, 'selling_price': 155.0, 'stock_quantity': 40, 'unit_size': 'Pack of 4 x 75g'}]},
    {   'brand': 'Dettol',
        'category_slug': 'pooja-samagri',
        'description': 'डेटॉल कुल मेंथॉल साबण. उन्हाळ्यात शरीराला देतो थंडगार ताजेतवानेपणा.',
        'image_url': '/products/dettol-cool-soap-pack4.jpg',
        'is_loose': False,
        'name': 'Dettol Cool Menthol Soap (Pack of 4 x 75g)',
        'name_hi': 'डेटॉल कुल मेंथॉल साबण (४ साबणाचा पॅक)',
        'variants': [{'mrp': 155.0, 'selling_price': 155.0, 'stock_quantity': 40, 'unit_size': 'Pack of 4 x 75g'}]},
    {   'brand': 'Dettol',
        'category_slug': 'pooja-samagri',
        'description': 'डेटॉल ओरिजिनल लिक्विड हँडवॉश रीफिल पॅक. हात स्वच्छ व जंतूमुक्त ठेवण्यासाठी.',
        'image_url': '/products/dettol-handwash-refill-175ml.jpg',
        'is_loose': False,
        'name': 'Dettol Liquid Handwash Original (175ml Refill Pouch)',
        'name_hi': 'डेटॉल लिक्विड हँडवॉश रीफिल पाउच (१७५ मिली)',
        'variants': [{'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 50, 'unit_size': '175ml Refill Pouch'}]},
    {   'brand': 'Lux',
        'category_slug': 'pooja-samagri',
        'description': 'लक्स रोझ आणि व्हिटॅमिन सी समृद्ध सौंदर्य साबण. त्वचेला देतो मऊपणा आणि चमक.',
        'image_url': '/products/lux-soft-glow-rose-100g.jpg',
        'is_loose': False,
        'name': 'Lux Soft Glow Rose Bathing Soap (100g Bar)',
        'name_hi': 'लक्स रोझ सॉफ्ट ग्लो आंघोळीचा साबण (१०० ग्रॅम)',
        'variants': [{'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 60, 'unit_size': '100g Bar'}]},
    {   'brand': 'Margo',
        'category_slug': 'pooja-samagri',
        'description': '१००% शुद्ध कडूनिंबाच्या तेलापासून बनवलेला नैसर्गिक अँटी-बॅक्टेरियल साबण.',
        'image_url': '/products/margo-neem-soap-100g.jpg',
        'is_loose': False,
        'name': 'Margo Original Neem Bathing Soap (100g Bar)',
        'name_hi': 'मार्गॊ ओरिजिनल कडुलिंब साबण (१०० ग्रॅम)',
        'variants': [{'mrp': 35.0, 'selling_price': 35.0, 'stock_quantity': 60, 'unit_size': '100g Bar'}]},
    {   'brand': 'Moti',
        'category_slug': 'pooja-samagri',
        'description': 'महाराष्ट्राचा पारंपरिक मोती साबण. चंदनाचा अस्सल शाही सुगंध आणि टवटवीत त्वचा.',
        'image_url': '/products/moti-luxury-sandal-soap.jpg',
        'is_loose': False,
        'name': 'Moti Luxury Sandal Bath Soap (150g Bar)',
        'name_hi': 'मोती लक्झरी चंदन आंघोळीचा साबण (१५० ग्रॅम)',
        'variants': [{'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 40, 'unit_size': '150g Bar'}]},
    {   'brand': 'Clinic Plus',
        'category_slug': 'pooja-samagri',
        'description': 'क्लिनिक प्लस मिल्क प्रोटीन फॉर्म्युला १ रुपयाचा सॅशे. केसांच्या मजबुतीसाठी.',
        'image_url': '/products/clinic-plus-sachet-1rs.jpg',
        'is_loose': False,
        'name': 'Clinic Plus Strong & Long Shampoo (₹1 Sachet)',
        'name_hi': 'क्लिनिक प्लस शाम्पू (१ रुपया सॅशे)',
        'variants': [   {'mrp': 1.0, 'selling_price': 1.0, 'stock_quantity': 300, 'unit_size': '₹1 Sachet'},
                        {'mrp': 2.0, 'selling_price': 2.0, 'stock_quantity': 200, 'unit_size': '₹2 Sachet'}]},
    {   'brand': 'Clinic Plus',
        'category_slug': 'pooja-samagri',
        'description': 'क्लिनिक प्लस मिल्क प्रोटीन शाम्पू बाटली.',
        'image_url': '/products/clinic-plus-shampoo-bottle.jpg',
        'is_loose': False,
        'name': 'Clinic Plus Strong & Long Shampoo (80ml / 175ml Bottle)',
        'name_hi': 'क्लिनिक प्लस शाम्पू बाटली (८० मिली / १७५ मिली)',
        'variants': [   {'mrp': 50.0, 'selling_price': 50.0, 'stock_quantity': 40, 'unit_size': '80ml Bottle'},
                        {'mrp': 120.0, 'selling_price': 120.0, 'stock_quantity': 25, 'unit_size': '175ml Bottle'}]},
    {   'brand': 'Dove',
        'category_slug': 'pooja-samagri',
        'description': 'डव्ह डेली शाइन न्यूट्रिटिव्ह सीरम शाम्पू २ रुपयांचा सॅशे.',
        'image_url': '/products/dove-shampoo-sachet-2rs.jpg',
        'is_loose': False,
        'name': 'Dove Daily Shine Shampoo (₹2 Sachet)',
        'name_hi': 'डव्ह डेली शाइन शाम्पू (२ रुपये सॅशे)',
        'variants': [{'mrp': 2.0, 'selling_price': 2.0, 'stock_quantity': 200, 'unit_size': '₹2 Sachet'}]},
    {   'brand': 'Dove',
        'category_slug': 'pooja-samagri',
        'description': 'डव्ह डेली शाइन शाम्पू १८० मिली बाटली. केसांना देतो मऊपणा आणि नैसर्गिक चमक.',
        'image_url': '/products/dove-shampoo-bottle-180ml.jpg',
        'is_loose': False,
        'name': 'Dove Daily Shine Shampoo (180ml Bottle)',
        'name_hi': 'डव्ह डेली शाइन शाम्पू (१८० मिली बाटली)',
        'variants': [{'mrp': 175.0, 'selling_price': 175.0, 'stock_quantity': 25, 'unit_size': '180ml Bottle'}]},
    {   'brand': 'Sunsilk',
        'category_slug': 'pooja-samagri',
        'description': 'सनसिल्क ब्लॅक शाइन १ रुपया सॅशे. आवळा व तेल फॉर्म्युला चकचकीत काळ्या केसांसाठी.',
        'image_url': '/products/sunsilk-sachet-1rs.jpg',
        'is_loose': False,
        'name': 'Sunsilk Black Shine Shampoo (₹1 Sachet)',
        'name_hi': 'सनसिल्क ब्लॅक शाइन शाम्पू (१ रुपया सॅशे)',
        'variants': [{'mrp': 1.0, 'selling_price': 1.0, 'stock_quantity': 300, 'unit_size': '₹1 Sachet'}]},
    {   'brand': 'Sunsilk',
        'category_slug': 'pooja-samagri',
        'description': 'सनसिल्क स्टनिंग ब्लॅक शाइन १८० मिली बाटली.',
        'image_url': '/products/sunsilk-bottle-180ml.jpg',
        'is_loose': False,
        'name': 'Sunsilk Black Shine Shampoo (180ml Bottle)',
        'name_hi': 'सनसिल्क ब्लॅक शाइन शाम्पू (१८० मिली बाटली)',
        'variants': [{'mrp': 160.0, 'selling_price': 160.0, 'stock_quantity': 25, 'unit_size': '180ml Bottle'}]},
    {   'brand': 'Head & Shoulders',
        'category_slug': 'pooja-samagri',
        'description': 'हेड अँड शोल्डर डँड्रफ मुळापासून घालवणारा आणि केसांना रेशमी मऊ ठेवणारा शाम्पू.',
        'image_url': '/products/head-shoulders-smooth-silky-180ml.jpg',
        'is_loose': False,
        'name': 'Head & Shoulders Anti-Dandruff Smooth & Silky Shampoo (180ml)',
        'name_hi': 'हेड अँड शोल्डर अँटी डँड्रफ शाम्पू (१८० मिली बाटली)',
        'variants': [{'mrp': 185.0, 'selling_price': 185.0, 'stock_quantity': 25, 'unit_size': '180ml Bottle'}]},
    {   'brand': 'Head & Shoulders',
        'category_slug': 'pooja-samagri',
        'description': 'हेड अँड शोल्डर कुल मेंथॉल शाम्पू ७२ मिली बाटली. डोक्याला देतो ताजेतवाने गारवा.',
        'image_url': '/products/head-shoulders-cool-menthol-72ml.jpg',
        'is_loose': False,
        'name': 'Head & Shoulders Cool Menthol Shampoo (72ml Bottle)',
        'name_hi': 'हेड अँड शोल्डर कुल मेंथॉल शाम्पू (७२ मिली बाटली)',
        'variants': [{'mrp': 85.0, 'selling_price': 85.0, 'stock_quantity': 30, 'unit_size': '72ml Bottle'}]},
    {   'brand': 'Dabur',
        'category_slug': 'pooja-samagri',
        'description': 'डाबर वाटिका आयुर्वेदिक हिना व आवळा शाम्पू. केसांना नैसर्गिक पोषण आणि मजबूती देतो.',
        'image_url': '/products/dabur-vatika-shampoo-180ml.jpg',
        'is_loose': False,
        'name': 'Dabur Vatika Henna & Amla Shampoo (180ml Bottle)',
        'name_hi': 'डाबर वाटिका हिना व आवळा शाम्पू (१८० मिली बाटली)',
        'variants': [{'mrp': 145.0, 'selling_price': 145.0, 'stock_quantity': 25, 'unit_size': '180ml Bottle'}]},
    {   'brand': 'Colgate',
        'category_slug': 'pooja-samagri',
        'description': 'कोलगेट स्ट्रॉंग टीथ कॅल्शियम व मिनरल्सयुक्त टूथपेस्ट. दातांना देतो पोलादी मजबूती.',
        'image_url': '/products/colgate-strong-teeth-paste.jpg',
        'is_loose': False,
        'name': 'Colgate Strong Teeth Dental Cream (100g / 150g)',
        'name_hi': 'कोलगेट स्ट्रॉंग टीथ पेस्ट (१०० ग्रॅम / १५० ग्रॅम)',
        'variants': [   {'mrp': 65.0, 'selling_price': 65.0, 'stock_quantity': 60, 'unit_size': '100g Tube'},
                        {'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 40, 'unit_size': '150g Tube'}]},
    {   'brand': 'Colgate',
        'category_slug': 'pooja-samagri',
        'description': 'कोलगेट मॅक्सफ्रेश कुलिंग क्रिस्टल्ससह. श्वासाला देतो दिवसभर टिकणारा ताजेतवाना सुगंध.',
        'image_url': '/products/colgate-maxfresh-peppermint.jpg',
        'is_loose': False,
        'name': 'Colgate MaxFresh Peppermint Ice Toothpaste (80g / 150g)',
        'name_hi': 'कोलगेट मॅक्सफ्रेश पेपरमिंट पेस्ट (८० ग्रॅम / १५० ग्रॅम)',
        'variants': [   {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 50, 'unit_size': '80g Tube'},
                        {'mrp': 110.0, 'selling_price': 110.0, 'stock_quantity': 30, 'unit_size': '150g Tube'}]},
    {   'brand': 'Dabur',
        'category_slug': 'pooja-samagri',
        'description': 'डाबर लाल दंतमंजन पेस्ट. लवंग व पुदिन्याने हिरड्यांच्या सर्व समस्यांवर रामबाण उपाय.',
        'image_url': '/products/dabur-red-paste.jpg',
        'is_loose': False,
        'name': 'Dabur Red Ayurvedic Toothpaste (100g / 150g)',
        'name_hi': 'डाबर रेड आयुर्वेदिक टूथपेस्ट (१०० ग्रॅम / १५० ग्रॅम)',
        'variants': [   {'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 60, 'unit_size': '100g Tube'},
                        {'mrp': 95.0, 'selling_price': 95.0, 'stock_quantity': 40, 'unit_size': '150g Tube'}]},
    {   'brand': 'Patanjali',
        'category_slug': 'pooja-samagri',
        'description': 'पतंजली दंतकांती. अकर्करा, बबूल व कडूनिंबायुक्त दातांचे नैसर्गिक आयुर्वेदिक सुरक्षा कवच.',
        'image_url': '/products/patanjali-dant-kanti-paste.jpg',
        'is_loose': False,
        'name': 'Patanjali Dant Kanti Dental Cream (100g / 200g)',
        'name_hi': 'पतंजली दंतकांती आयुर्वेदिक पेस्ट (१०० ग्रॅम / २०० ग्रॅम)',
        'variants': [   {'mrp': 55.0, 'selling_price': 55.0, 'stock_quantity': 60, 'unit_size': '100g Tube'},
                        {'mrp': 105.0, 'selling_price': 105.0, 'stock_quantity': 40, 'unit_size': '200g Tube'}]},
    {   'brand': 'Pepsodent',
        'category_slug': 'pooja-samagri',
        'description': 'पेप्सोडंट जर्मि चेक. जेवणानंतर १२ तास दातांमधील जंतूंशी लढा देणारी टूथपेस्ट.',
        'image_url': '/products/pepsodent-germi-check-100g.jpg',
        'is_loose': False,
        'name': 'Pepsodent Expert Protection Germi Check Toothpaste (100g)',
        'name_hi': 'पेप्सोडंट जर्मि चेक टूथपेस्ट (१०० ग्रॅम)',
        'variants': [{'mrp': 60.0, 'selling_price': 60.0, 'stock_quantity': 50, 'unit_size': '100g Tube'}]},
    {   'brand': 'Sensodyne',
        'category_slug': 'pooja-samagri',
        'description': 'दात आंबणे आणि सेन्सिटिव्हिटीवर डॉक्टरांनी शिफारस केलेली नंबर १ टूथपेस्ट.',
        'image_url': '/products/sensodyne-daily-care-75g.jpg',
        'is_loose': False,
        'name': 'Sensodyne Daily Care Cool Mint Toothpaste (75g)',
        'name_hi': 'सेन्सॊडाइन डेली केअर कूल मिंट पेस्ट (७५ ग्रॅम)',
        'variants': [{'mrp': 135.0, 'selling_price': 135.0, 'stock_quantity': 35, 'unit_size': '75g Tube'}]},
    {   'brand': 'Parachute',
        'category_slug': 'pooja-samagri',
        'description': 'पॅराशूट १००% शुद्ध खोबरेल तेल. हाताने निवडलेल्या सुक्या खोबऱ्यापासून बनवलेले खाद्य दर्जाचे '
                       'तेल.',
        'image_url': '/products/parachute-coconut-oil.jpg',
        'is_loose': False,
        'name': 'Parachute 100% Pure Coconut Hair Oil (100ml / 200ml / 500ml)',
        'name_hi': 'पॅराशूट १००% शुद्ध खोबरेल तेल (१०० मिली / २०० मिली / ५०० मिली)',
        'variants': [   {'mrp': 45.0, 'selling_price': 45.0, 'stock_quantity': 60, 'unit_size': '100ml Bottle'},
                        {'mrp': 90.0, 'selling_price': 90.0, 'stock_quantity': 40, 'unit_size': '200ml Bottle'},
                        {'mrp': 210.0, 'selling_price': 210.0, 'stock_quantity': 25, 'unit_size': '500ml Bottle'}]},
    {   'brand': 'Cycle Pure',
        'category_slug': 'pooja-samagri',
        'description': 'सायकल थ्री इन वन अगरबत्ती. मंद आणि पवित्र सुगंधाने घर प्रसन्न करणारी अगरबत्ती.',
        'image_url': '/products/cycle-three-in-one-agarbatti.jpg',
        'is_loose': False,
        'name': 'Cycle Pure Three in One Agarbatti (Pooja Incense Sticks)',
        'name_hi': 'सायकल थ्री इन वन अगरबत्ती (पूजा साहित्य)',
        'variants': [   {'mrp': 20.0, 'selling_price': 20.0, 'stock_quantity': 80, 'unit_size': 'Standard Pack'},
                        {'mrp': 65.0, 'selling_price': 65.0, 'stock_quantity': 40, 'unit_size': 'Jumbo Box'}]}]
